### ISSUE TITLE
配置的时候可以通过，但是发送消息就一直提示 请求校验失败

### ISSUE THREAD

**Issue by lancelot96** [silenceper/wechat#10]
如题
打印出timestamp， nonce， signature都是空的

**Comment by silenceper** [comment]
能把代码贴下吗，看下是怎么发送消息的，怎么配置的？

**Comment by silenceper** [comment]
"请求校验失败" 的提示是在收到微信消息校验的时候返回的，可以抓个包看下微信返回的信息。
从上面的代码看不出大问题。

`examples`目录下的例子能否跑通？

**Comment by lancelot96** [comment]
唉 配置能通过啊
examples没试过 明天试试

**Comment by changyu72** [comment]
例子存在同样的问题："请求校验失败"

**Comment by lancelot96** [comment]
我把我的解决方案说一下
修改作者的代码 在验证的地方加一个条件 如果是get方法就验证

**Comment by silenceper** [comment]
能否提供一个pr，我这边排查下 ，谢谢。
