### ISSUE TITLE
自定义菜单问题

### ISSUE THREAD

**Issue by wispedia** [silenceper/wechat#125]
![image](https://user-images.githubusercontent.com/15278300/58109336-0a975b80-7c20-11e9-89b0-a8d4618c9d28.png)
![image](https://user-images.githubusercontent.com/15278300/58109361-1551f080-7c20-11e9-8b0b-c079074e3384.png)
GetMenu()哪里有参数哦

**Comment by silenceper** [comment]
这个文档上有问题，不需要参数

**Comment by silenceper** [comment]
fix #126
