### ISSUE TITLE
消息解密出错，the amount to pad is incorrect

### ISSUE THREAD

**Issue by cr0z** [silenceper/wechat#13]
您好，我在使用的过程中遇到了以下错误：  
`the amount to pad is incorrect: 103`  
对AES不太了解，不知道是什么原因造成的呢？望赐教  
https://github.com/silenceper/wechat/blob/master/util/crypto.go#L139

**Comment by silenceper** [comment]
这是在微信返回的密文中，解密的时候出现的错误。
情况是不管微信返回哪种消息都是报这个错么？
在公众平台将 “消息加解密方式” 设置为兼容模式，看下微信返回的明文以及密文是什么？

**Comment by singsenxc** [comment]
是的，用的是明文模式是正常的，安全和兼容模式所有消息都解密报错
微信发送过来的消息为：
`map[msg_signature:[16d171186cb1c7b50f21393445f7b6e06badd51b] signature:[d95256de9800ecd4dfb537a9e568dc0b46d4cdaf] timestamp:[1483081045] nonce:[1938463495] openid:[xxxxxxxxxxxxxxxxxxxxxxxxxxxx] encrypt_type:[aes]]`
body的内容为:
`
 <xml>
    <ToUserName><![CDATA[gh_300f1ebbd4d0]]></ToUserName>
    <FromUserName><![CDATA[oGhJFwaBkSW8fYK1Nszv_gudio2c]]></FromUserName>
    <CreateTime>1483081045</CreateTime>
    <MsgType><![CDATA[event]]></MsgType>
    <Event><![CDATA[VIEW]]></Event>
    <EventKey><![CDATA[http://xxxx/newest]]></EventKey>
    <MenuId>439342175</MenuId>
    <Encrypt><![CDATA[Q7Gh1SzKc7E1kwjVh3QK1eezQxn+PGvXKfJy90r6aEHtDqFfwZ7EGqGJNqQGC4Mqu01ngbeeqrdCpNuvV2atExEIJj1lkV4K92OhogfSfp8gno/afc+pOo7glfH3ZxaU38wjSSa4il3O4xKvx5wS9vZTHtO7QtwrYv+juGdDIJRLChCeLmX2QO+8ziARYfBqWSZdpRPHHVXHHFoJin1j8snAqNa41LdAw/sNPbpLloxfuMl5cOpZosZxncNw8XsmZy+wpUYW37Qm4duOv3woOX6pSfqmekDLiggnK4wV4ZGYtIp0Zyn+TOzXagXfGRhQKJ9lzrO1DQ9Nzxw302UgTwSO0vAaUxUKbN6HzHCcTZ6bPcgCUEgUeUeaDDV09oBC2/QsYYDinRzZicIr+yi2ssBJULRnLVG0cyuKwQDKCS1ef4fuIQW3UBbdgdv2mx59+nvQ7xCew4pnm2QBUHE6Oq9TNVOigIZLsLiUQtASacizhMKU/2C5u29dkceI4q6l]]></Encrypt>
</xml>
`

**Comment by silenceper** [comment]
这是菜单点击事件，我暂时没法复现这种情况。
如果接收MsgType=text的文本消息能否正常？

**Comment by singsenxc** [comment]
MsgType=text也解密出错，我再检查一下我自己的逻辑，暂时没法解决就先搁置了，现在暂时使用明文模式
