### ISSUE TITLE
小程序手机号解析

### ISSUE THREAD

**Issue by NewsNIng** [silenceper/wechat#130]
目前看源码只解密了用户信息，可以考虑增加手机号解密吗？
`
type UserPhoneInfo struct {
	PhoneNumber    string `json:"phoneNumber"`
	PurePhoneNumber   string `json:"purePhoneNumber"`
	CountryCode  string `json:"countryCode"`
	Watermark struct {
		Timestamp int64  `json:"timestamp"`
		AppID     string `json:"appid"`
	} `json:"watermark"`
}
`
类似以上结构去调整 Decrypt 解密数据 这个方法 func (wxa *MiniProgram) Decrypt(sessionKey, encryptedData, iv string)

自己已经实现，希望SDK能补全

**Comment by cielu** [comment]
已支持
