### ISSUE TITLE
微信网页授权通过 code 获取到的access_token 的问题

### ISSUE THREAD

**Issue by JeffreyBool** [silenceper/wechat#132]
微信网页授权通过 code 获取到的access_token 需要缓存起来吗，是用来获取微信用户信息的。不是所有 api 的哪个access_token

**Comment by silenceper** [comment]
官方文档：https://mp.weixin.qq.com/wiki?action=doc&id=mp1421140842&t=0.888455262701805#1

**Comment by JeffreyBool** [comment]
但是有个问题。 这个 access_token 是和用户 open_id 绑定的。 是需要将 open_id 存到 Redis 之类吗

**Comment by silenceper** [comment]
如果缓存起来的话，肯定是要跟跟用户关联的

看自己情况是否需要缓存

**Comment by JeffreyBool** [comment]
这个access_token 有次数限制吗？是否和 全局access_token 一样有次数限制呢

**Comment by silenceper** [comment]
> 这个access_token 有次数限制吗？是否和 全局access_token 一样有次数限制呢

这个请查看官方文档
