### ISSUE TITLE
请问现在接收消息推送是不是不支持json格式的

### ISSUE THREAD

**Issue by OscarZhou** [silenceper/wechat#141]

**Comment by silenceper** [comment]
参考微信文档，是xml

https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_standard_messages.html

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_standard_messages.html">文本消息 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>
