### ISSUE TITLE
请问有打算支持qq小程序吗

### ISSUE THREAD

**Issue by chenhg5** [silenceper/wechat#145]
qq小程序文档：https://q.qq.com/wiki/develop/miniprogram/server/

**Comment by silenceper** [comment]
qq的不打算在这里支持了，建议另起一个项目

**Comment by chenhg5** [comment]
@silenceper 嗯嗯。从文档上看，流程跟微信小程序大部分是相同的，编码量不大。你如果可以起一个新项目，可以告知我吗，我这边可以支持下开发。
