### ISSUE TITLE
获取用户基本信息？

### ISSUE THREAD

**Issue by salamander-mh** [silenceper/wechat#146]
公众号也有接口获取用户基本信息，这个似乎没写
```
https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
```
[获取用户基本信息（包括UnionID机制）](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839)

**Comment by zinwalin** [comment]
FYI  

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839

**Comment by salamander-mh** [comment]
这个接口是有的
