### ISSUE TITLE
用go mod 获取包时，获取的是tag v1.0.0 ，就不是最新的包

### ISSUE THREAD

**Issue by 1458790210** [silenceper/wechat#148]
![QQ截图20190820181314](https://user-images.githubusercontent.com/17975344/63338848-38528480-c376-11e9-89ae-db9ab785c0f1.png)

**Comment by silenceper** [comment]
在go mod模式下，可以指定master就可以获取到最新的包

 `go get -v github.com/silenceper/wechat@master`
