### ISSUE TITLE
NewWechat怎么实现单例模式？

### ISSUE THREAD

**Issue by zinwalin** [silenceper/wechat#149]
```
memCache=cache.NewMemcache("127.0.0.1:11211")

//配置微信参数
config := &wechat.Config{
	AppID:          "xxxx",
	AppSecret:      "xxxx",
	Token:          "xxxx",
	EncodingAESKey: "xxxx",
	Cache:          memCache
}
wc := wechat.NewWechat(config)
```

NewWechat初始化后， 需要在多处用到wc这个对象。

**Comment by mojiajuzi** [comment]
1. create new floder as new package
1. import `silenceper/wechat`  package
1. init wechat in the `init` function
1. import the wechat object

**Comment by zinwalin** [comment]
> 1. create new floder as new package
> 2. import `silenceper/wechat`  package
> 3. init wechat in the `init` function
> 4. import the wechat object

thanks a lot.
