### ISSUE TITLE
access token过期的问题是怎么解决的？

### ISSUE THREAD

**Issue by zinwalin** [silenceper/wechat#150]
这个项目有实现自动更新access token的功能吗？   还是说需要每次自己检查access token的有效性？

`template msg send error : errcode=40001 , errmsg=invalid credential, access_token is invalid or not latest hint: [3koVtA0338hkb5!]`

**Comment by RE-Roger** [comment]
有的，从微信服务器更新accesstoken写入cache的时候就设置了过期时间，

`err = ctx.Cache.Set(accessTokenCacheKey, resAccessToken.AccessToken, time.Duration(expires)*time.Second)`

这个cache interface 实现了过期后get会返回nil，在获取到nil后就会重亲去服务器获取accesstoken
```
        val := ctx.Cache.Get(accessTokenCacheKey)
	if val != nil {
		accessToken = val.(string)
		return
	}

       //从微信服务器获取

	var resAccessToken ResAccessToken
	resAccessToken, err = ctx.GetAccessTokenFromServer()
	if err != nil {
		return
	}
```

**Comment by zinwalin** [comment]
懂了， 感谢

**Comment by go-app-cloud** [comment]
反馈一下，在线上运行十几个小时候会出现template msg send error : errcode=40001 , errmsg=invalid credential, access_token is invalid or not latest。

**Comment by silenceper** [comment]
> 反馈一下，在线上运行十几个小时候会出现template msg send error : errcode=40001 , errmsg=invalid credential, access_token is invalid or not latest。

有更多的log信息吗，用的什么cache来村access_token，看下access_token 的失效时间

**Comment by go-app-cloud** [comment]
缓存使用cache.NewMemory(),没有使用第三方缓存服务器

**Comment by zibber2015** [comment]
post方法需要判断一下接口返回 40001也应该刷新一下token

**Comment by athom** [comment]
> post方法需要判断一下接口返回 40001也应该刷新一下token

对头,这里有个bug, 就是cache可能还没过期, 但是接口却返回40001, 可能是cache的过期时间和实际过期时间不一致.
保险的办法就是在所有post返回400001的时候统一再刷新, 最好再重试.
看了下master代码不太好改, 不知道release2里面有改进没有

@silenceper

**Comment by silenceper** [comment]
这里要判定40001错误是cache出现了问题导致的，还是`cache的过期时间和实际过期时间不一致.`

避免token调用次数被耗尽

**Comment by athom** [comment]
> 缓存使用cache.NewMemory(),没有使用第三方缓存服务器
我和楼上用的一样类型的cache, 都是inmemory的
也都是跑了一段时间后才爆发出来的.
你说的cache出现问题, 是说这个Memory实现的cache的逻辑问题吗?
粗粗看了下, Get的时候没有Lock,可能是个问题, 你可以重点看看. 
同理, IsExist也没有Lock, 而且似乎没有被用到. 

另外看了你是提前25分钟,就开始刷新, 
https://github.com/silenceper/wechat/blob/5d9705ddc82c668ce34d2c390d3074b7678393d4/credential/default_access_token.go#L73 
请教下这里有什么经验之谈吗?

anyway, 建议个可以加下日志, 然后通过环境变量来开启或者关闭, 这样方便调试... 

@silenceper

**Comment by silenceper** [comment]
cache 先让token失效，而不是等到token真正失效的时候再去刷新，再去做这件事。这里token的刷新是一个被动刷新的逻辑。

可以在这里加个日志。

**Comment by letsfire** [comment]
我也碰到这个问题，不是BUG。应该是大家使用的问题。我纠结了好久，其实是我自己在测试环境和生产环境都部署了，所以存在两个服务更新同一个公众号的token

**Comment by ticktap** [comment]
> 我也碰到这个问题，不是BUG。应该是大家使用的问题。我纠结了好久，其实是我自己在测试环境和生产环境都部署了，所以存在两个服务更新同一个公众号的token

请问你最后怎么解决这个问题的？

**Comment by chenyu1990** [comment]
@silenceper 能判断40001自动去更新redis里的access_token吗？现在在生产环境，仍然会出现40001的错误。。两台服务器连的同一个redis。
