### ISSUE TITLE
放个捐款的二维码吧

### ISSUE THREAD

**Issue by zinwalin** [silenceper/wechat#152]
从这个项目学到了很多知识点，并节省了很多开发和调试时间， 非常感谢。

**Comment by silenceper** [comment]
很高兴您能够从这个项目中学到知识点，同时我也希望依赖社区的力量，让这个SDK成为Golang中最方便、易用的wechat sdk，也是我开源这个项目的初衷 💯

**Comment by 107295472** [comment]
现在最有名的是.net的盛派，希望你们做golang中最强的
