### ISSUE TITLE
微信菜单创建不成功

### ISSUE THREAD

**Issue by eiffelqiu** [silenceper/wechat#17]
我的代码是这样的

	mu := wc.GetMenu(c.Request, c.Writer)

	buttons := make([]*menu.Button, 1)
	btn := new(menu.Button)
	btn.SetClickButton("name", "key123")
	buttons[0] = btn

	//发送请求
	err2 := mu.SetMenu(buttons)
	if err2 != nil {
		log.Printf("err= %v", err2)
		return
	}

日志报错是：

	err2 := mu.SetMenu(buttons)

这条引发的错误

错误是：

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:489 (0x42866f)
/usr/local/go/src/runtime/panic.go:63 (0x42751e)
/usr/local/go/src/runtime/signal_unix.go:290 (0x43d43f)
/Users/xxxx/go/src/github.com/silenceper/wechat/context/access_token.go:36 (0x77651b)
/Users/xxxx/go/src/github.com/silenceper/wechat/menu/menu.go:123 (0x77d0d3)
/Users/xxxx/projects/golang/wx/main.go:57 (0x7863db)

**Comment by silenceper** [comment]
从错误来看，好像是没有设置cache，access_token是放在cache中的，在`wechat.Config`中设置memcache

**Comment by eiffelqiu** [comment]
谢谢， 还真是这个原因， 安装了 memcached 启动， 并设置就可以了。
只是有些奇怪，普通微信服务使用 memached 感觉有点重

**Comment by silenceper** [comment]
普通微信服务，怎么理解？
因为微信的的access_token 每天是有次数限制的，如果每天的请求数量超过这一限制，当天的服务不可用，影响更大。 所以就得寻求一个可靠存储介质来保存，避免超限！  这个需要你自己来评估，其他存储方案，只要实现 [cache/cache.go](https://github.com/silenceper/wechat/blob/master/cache/cache.go#L6) 接口就行了

**Comment by eiffelqiu** [comment]
我的意思是你可以用一个 sqlite 之类的本地数据库来存储比较好， 否则要依赖用户另外装一个 memcached 服务才能运行该程序，就有一点太“重”了。

**Comment by silenceper** [comment]
可能因为你只用到了菜单设置，所以看起来取数access_token并不那么频繁。
如果在用到了网页授权或者其他需要频繁取access_token的场景，可能就需要考虑效率的问题了。
