### ISSUE TITLE
消息模板如何做到自动识别发送？

### ISSUE THREAD

**Issue by zinwalin** [silenceper/wechat#171]
消息模板存入数据库后， 消息模板是有增删的可能。  代码里面怎么做到自动从数据库取得所要的template id， 并发送？   

比如，有个模板“购买成功通知”， template id是 skdfjssd,   代码里怎么自动知道需要用哪个模板发送？   此模板有可能删除，添加新的更美观的模板。

**Comment by silenceper** [comment]
这个可以将template id和要发送的业务类型做一个关联表，代码中根据业务类型（比如固定的一个CODE），查找到template 即可，之后即便删除了 就在代码中做好边界判断了

**Comment by zinwalin** [comment]
> 这个可以将template id和要发送的业务类型做一个关联表，代码中根据业务类型（比如固定的一个CODE），查找到template 即可，之后即便删除了 就在代码中做好边界判断了

有道理，谢谢建议。
