### ISSUE TITLE
能否增加各主要接口的example

### ISSUE THREAD

**Issue by zinwalin** [silenceper/wechat#172]
比如，微信支付(预支付，正式支付）， 集成过程中， 会碰到大量的问题， 签名/参数/配置，如果有示例，会减少开发人员的大量时间。

**Comment by silenceper** [comment]
v2版本准备新增[example](https://github.com/gowechat/example)实例
同时提供文档：https://silenceper.com/wechat

**Comment by silenceper** [comment]
参考v2版本example示例
