### ISSUE TITLE
found, but does not contain package github.com/silenceper/wechat

### ISSUE THREAD

**Issue by qialie** [silenceper/wechat#176]
build go-cms: cannot load github.com/silenceper/wechat: module github.com/silenceper/wechat@latest (v2.0.0+incompatible) found, but does not contain package github.com/silenceper/wechat

**Comment by qialie** [comment]
build command-line-arguments: cannot load github.com/silenceper/wechat: module github.com/silenceper/wechat@latest (v2.0.0+incompatible) found, but does not contain package github.com/silenceper/wechat

**Comment by qialie** [comment]
github.com/silenceper/wechat v2.0.0+incompatible h1:3vbX2Vek+vtlhGAZX8dMGRGfxRRuhXn8xrEi0EzTYBI=
github.com/silenceper/wechat v2.0.0+incompatible/go.mod h1:JKAk3URsmQk11QCP/n3xq71Z5XdtCaLI61zRNbhFdVk=

**Comment by silenceper** [comment]
```
go get https://github.com/silenceper/wechat@1.2.6
```
