### ISSUE TITLE
同样建议切换为go-redis

### ISSUE THREAD

**Issue by libra1010** [silenceper/wechat#177]
现目前redis不支持 哨兵，集群。 有很多还是不方便。 建议 切换为go-redis 并支持 哨兵，集群

**Comment by housemea** [comment]
> go-redis

切换为 ：https://github.com/go-redis/redis ？

<blockquote><img src="https://opengraph.githubassets.com/323d1195ee7a669850a77c9859f998f5727932103520c577c29c802f47ec8e34/go-redis/redis" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/go-redis/redis">GitHub - go-redis/redis: Type-safe Redis client for Golang</a></strong></div><div>Type-safe Redis client for Golang. Contribute to go-redis/redis development by creating an account on GitHub.</div></blockquote>

**Comment by silenceper** [comment]
fixed in #546
