### ISSUE TITLE
example的http样例未跑通，求解

### ISSUE THREAD

**Issue by duncanwang** [silenceper/wechat#189]
## 问题及现象
采用V2.0.0的代码，运行go  run http.go后，
在浏览器页面输入 https://dev.morvoo.com/apis/后，提示“请求校验失败”。
看下样例代码，并没有使用memCache=cache.NewMemcache("127.0.0.1:11211")的配置。
这个影响吗？

**Comment by silenceper** [comment]
`wechat.Config`中的参数设置对吗？

**Comment by duncanwang** [comment]
参数对的。我采用V2.0.0的版本，集成成功。在公众号输入"hello"，会有panic产生。

root@iZuf61lyoku3o73ozrd7x1Z:/opt/GOPATH/src/github.com/silenceper/wechat-2.0.0/examples/http# go run http.go


panic error: reflect: Call using message.CDATA as type string
goroutine 5 [running]:
runtime/debug.Stack(0xc00010b2b8, 0x798540, 0xc0000138a0)
	/opt/module/go/src/runtime/debug/stack.go:24 +0x9d
github.com/silenceper/wechat/server.(*Server).buildResponse.func1(0xc00010b728)
	/opt/GOPATH/src/github.com/silenceper/wechat/server/server.go:172 +0x60
panic(0x798540, 0xc0000138a0)

**Comment by silenceper** [comment]
你拉取最新的代码再重试下

**Comment by silenceper** [comment]
v2.0.0代码是没问题的

**Comment by duncanwang** [comment]
> v2.0.0代码是没问题的
能邮件建立一个联系吗？我这儿还是没有测试过。我这儿后面可能还有项目合作机会。我的邮箱：duncan.wang@artarva.com

**Comment by silenceper** [comment]
> > v2.0.0代码是没问题的
> > 能邮件建立一个联系吗？我这儿还是没有测试过。我这儿后面可能还有项目合作机会。我的邮箱：[duncan.wang@artarva.com](mailto:duncan.wang@artarva.com)

参考 github profile
