### ISSUE TITLE
偶尔会报请求校验失败。

### ISSUE THREAD

**Issue by edl7878** [silenceper/wechat#19]
这个代码很规范，谢谢！
用的example里的代码，仅仅改了监听端口，在debug时该错误反复出现，但是直接运行编译后的exe，没有错误输出。但是该错误似乎对功能没有任何影响。

package main

import (
	"fmt"
	"net/http"

	"github.com/silenceper/wechat"
	"github.com/silenceper/wechat/message"
)

func hello(rw http.ResponseWriter, req *http.Request) {

	//配置微信参数
	config := &wechat.Config{
		AppID:          "...",
		AppSecret:      "...",
		Token:          "...",
		EncodingAESKey: "...",
	}
	wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	//设置接收消息的处理方法
	server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {

		//回复消息：演示回复用户发送的消息
		text := message.NewText(msg.Content)
		return &message.Reply{message.MsgTypeText, text}
	})

	//处理消息接收以及回复
	err := server.Serve()
	if err != nil {
		fmt.Println(err)
		return
	}
	//发送回复的消息
	server.Send()
}

func main() {
	http.HandleFunc("/", hello)
	err := http.ListenAndServe(":80", nil)
	if err != nil {
		fmt.Printf("start server error , err=%v", err)
	}
}

**Comment by silenceper** [comment]
请求校验失败时候的request信息是什么？ 微信请求的nonce，timestamp, signature 这些参数

**Comment by edl7878** [comment]
它偶尔发作，问题不好复现。
会不会是有人攻击服务器，假的request呢？
因为收发信息都正常的。

**Comment by silenceper** [comment]
不确定，得具体拿到request信息才能识别

**Comment by edl7878** [comment]
Validate called:
timestamp:
nonce:
signature:
请求校验失败
失败时是空值。

**Comment by silenceper** [comment]
攻击的可能能应该有点小，
看到请求的值都是空值的话，看下是在请求的时间点，是在回复了公众号出现，还是会自动出现
应该不是微信发送的request，可能是其他地方发送了request，
