### ISSUE TITLE
配置代码的效率

### ISSUE THREAD

**Issue by edl7878** [silenceper/wechat#20]
这个是例子中的代码，问题是，配置微信参数代码，写在请求回调函数里是不是合适呢？会不会影响效率，还是必须写在这里，不能写在main里？
func hello(rw http.ResponseWriter, req *http.Request) {

	//配置微信参数
	config := &wechat.Config{
		AppID:          "your app id",
		AppSecret:      "your app secret",
		Token:          "your token",
		EncodingAESKey: "your encoding aes key",
	}
	wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	//设置接收消息的处理方法
	server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {

		//回复消息：演示回复用户发送的消息
		text := message.NewText(msg.Content)
		return &message.Reply{message.MsgTypeText, text}
	})

	//处理消息接收以及回复
	err := server.Serve()
	if err != nil {
		fmt.Println(err)
		return
	}
	//发送回复的消息
	server.Send()
}

func main() {
	http.HandleFunc("/", hello)
	err := http.ListenAndServe(":8001", nil)
	if err != nil {
		fmt.Printf("start server error , err=%v", err)
	}
}

**Comment by silenceper** [comment]
`NewWechat `这个方法是需要放在每个请求的里面的，内部Request，Response是贯穿整个请求，存放在`wechat.Context`中，每次请求都重新New
所以在高并发情况下，放全局的话就会Request，Response 会混淆

不过单独提出来，节省的是New对象的开销，感觉意义不大。

**Comment by edl7878** [comment]
好的，多谢！

**Comment by edl7878** [comment]
把config挪到全局了，这样没问题吧？

package main

import (
	"fmt"
	"net/http"

	"github.com/silenceper/wechat"
	"github.com/silenceper/wechat/cache"
	"github.com/silenceper/wechat/message"
)

var config *wechat.Config

func hello(rw http.ResponseWriter, req *http.Request) {

	//打印request基本信息
	fmt.Print(req.RequestURI, "\n")
	//fmt.Print(req.PostForm, "\n")
	//配置微信参数:挪到main包全局变量中

	wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	fmt.Println(req.URL.RawQuery)
	//设置接收消息的处理方法
	server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {

		//回复消息：演示回复用户发送的消息
		text := message.NewText(msg.Content)

		fmt.Printf("Message received:%s\n\n", msg.Content)
		return &message.Reply{message.MsgTypeText, text}
	})

	//处理消息接收以及回复
	err := server.Serve()
	if err != nil {
		fmt.Println(err)
		return
	}
	//发送回复的消息
	server.Send()
}

func main() {

	//memcache = cache.NewMemcache("127.0.0.1:11211")
	config = &wechat.Config{
		AppID:          "...",
		AppSecret:      "...",
		Token:          "...",
		EncodingAESKey: "...",
		Cache:          cache.NewMemcache("127.0.0.1:11211"),
	}

	http.HandleFunc("/", hello)
	err := http.ListenAndServe(":80", nil)
	if err != nil {
		fmt.Printf("start server error , err=%v", err)
	}
}
