### ISSUE TITLE
VerifySign，NotifyResult不兼容使用了代金劵的情况

### ISSUE THREAD

**Issue by abotoo** [silenceper/wechat#203]
## VerifySign

使用了代金劵券的时候，NotifyResult中带有coupon_开头的一些字段，造成VerifySign验证返回错误

**Comment by HandsomeTiger** [comment]
我也遇到了同样类似的问题，用户在支付时使用推荐的银行卡减免部分缴纳金额，会在VerifySign 验签时失败。

**Comment by quxiaolong1504** [comment]
https://github.com/silenceper/wechat/pull/221
@silenceper  希望可以合并。
