### ISSUE TITLE
build command-line-arguments: cannot load github.com/silenceper/wechat: module github.com/silenceper/wechat@latest found (v2.0.1+incompatible), but does not contain package github.com/silenceper/wechat

### ISSUE THREAD

**Issue by xiya-vip** [silenceper/wechat#213]
## 问题及现象
<!-- 描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by xiya-vip** [comment]
build command-line-arguments: cannot load github.com/silenceper/wechat: module github.com/silenceper/wechat@latest found (v2.0.1+incompatible), but does not contain package github.com/silenceper/wechat

**Comment by silenceper** [comment]
请使用 v1.2.3 包，谢谢
