### ISSUE TITLE
微信接入时有个url验证，不知道sdk中有没有支持？

### ISSUE THREAD

**Issue by holdno** [silenceper/wechat#215]
## 问题及现象

参见官方文档：
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html

**Comment by silenceper** [comment]
肯定有

**Comment by holdno** [comment]
这个操作是在哪里呢？

**Comment by silenceper** [comment]
https://github.com/silenceper/wechat/blob/master/server/server.go#L51 从这里看下去

**Comment by rebider** [comment]
mark
