### ISSUE TITLE
请问，如果平台设置为安全模式，这个代码的回复消息，是安全模式还是混合模式呢？

### ISSUE THREAD

**Issue by edl7878** [silenceper/wechat#22]
func hello(rw http.ResponseWriter, req *http.Request) {

	//打印request基本信息
	fmt.Print(req.RequestURI, "\n")
	//fmt.Print(req.PostForm, "\n")
	//配置微信参数
	memcache := cache.NewMemcache("127.0.0.1:11211")
	config := &wechat.Config{
		AppID:          "...",
		AppSecret:      "...",
		Token:          "...",
		EncodingAESKey: "...",
		Cache:          memcache,
	}
	wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	fmt.Println(req.URL.RawQuery)
	//设置接收消息的处理方法
	server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {

		//回复消息：演示回复用户发送的消息
		text := message.NewText(msg.Content)

		fmt.Printf("Message received:%s\n\n", msg.Content)
		return &message.Reply{message.MsgTypeText, text}
	})

	//处理消息接收以及回复
	err := server.Serve()
	if err != nil {
		fmt.Println(err)
		return
	}
	//发送回复的消息
	server.Send()
}

**Comment by silenceper** [comment]
根据平台设置的规则返回，要不然就出错了。
see:https://github.com/silenceper/wechat/blob/master/server/server.go#L78
