### ISSUE TITLE
redisgo 依赖的问题

### ISSUE THREAD

**Issue by fxk2006** [silenceper/wechat#234]
`ambiguous import: found package github.com/gomodule/redigo/redis in multiple modules:
 github.com/gomodule/redigo v2.0.0+incompatible (F:\go_workspace\pkg\mod\github.com\gomodule\redigo@v2.0.0+incompatible\redis)
github.com/gomodule/redigo/redis v0.0.0-20200429221454-e14091dffc1b (F:\go_workspace\pkg\mod\github.com\gomodule\redigo\redis@v0.0.0-20200429221454-e14091dffc1b)`

**Comment by silenceper** [comment]
go.mod看一下

**Comment by silenceper** [comment]
fix in #237
