### ISSUE TITLE
结合beego  验证失败 http: wrote more than the declared Content-Length

### ISSUE THREAD

**Issue by nosix-me** [silenceper/wechat#25]
2017/08/07 14:42:14 [C] [asm_amd64.s:514] Handler crashed with error http: wrote more than the declared Content-Length
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/panic.go:489
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/github.com/silenceper/wechat/context/render.go:18
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/github.com/silenceper/wechat/context/render.go:25
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/github.com/silenceper/wechat/server/server.go:51
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/jrqs/service/weixinService.go:33
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/jrqs/controllers/message.go:14
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /opt/gopath/src/github.com/astaxie/beego/router.go:798
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:2568
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:1825
2017/08/07 14:42:14 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:2197

**Comment by silenceper** [comment]
每次必现么? 
beego版本是多少？

**Comment by nosix-me** [comment]
beego 1.8.3版本,对beego的返回结果处理流程是还不是很清楚，问题的原因应该是wechat处理后直接返回结果，beego处理流程中有其它处理造成的，wechat以后会考虑通过server获取返回结果，交给beego或者其它web框架控制返回结果吗

**Comment by silenceper** [comment]
请问你是在处理哪种情况出错的，是在接口配置信息配置接口地址失败了？

我用beego 1.8.3 ，beego1.9 没有复现这样的报错 

你的go版本是多少

**Comment by nosix-me** [comment]
go的版本 1.8.3 写的方式和例子中的代码可以跑 如果使用beego的工程 该如何结合
代码如下

package controllers

import (
	"github.com/astaxie/beego"
	"jrqs/service"
)

type MessageController struct {
	beego.Controller
}

func (msg *MessageController) Post() {
	msg.ServeXML()
	service.Handle(msg.Ctx)
	return
}

package service

import (
	"github.com/silenceper/wechat"
	"github.com/silenceper/wechat/message"
	"fmt"
	"github.com/astaxie/beego/context"
	"jrqs/utils"
	"strconv"
)

var config *wechat.Config

func init() {
	config = &wechat.Config{
		AppID:          "",
		AppSecret:      "",
		Token:          "",
		EncodingAESKey: "",
	}
}

func Handle(ctx *context.Context) {
	wc := wechat.NewWechat(config)
	server := wc.GetServer(ctx.Request, ctx.ResponseWriter)

	//设置接收消息的处理方法
	server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {
		switch msg.MsgType {
		case message.MsgTypeLocation:
			lat := strconv.FormatFloat(msg.LocationX,'f',10,64);
			lon :=strconv.FormatFloat(msg.LocationY,'f',10,64);
			label := msg.Label
			result := utils.GetNowcast(lat,lon)
			result = label+"\r\n"+result
			text :=message.NewText(result)
			return &message.Reply{message.MsgTypeText, text}
		case message.MsgTypeVoice:
			voice := message.NewVoice(msg.MediaID)
			return &message.Reply{message.MsgTypeVoice, voice}
		case message.MsgTypeEvent:
			switch msg.Event {
			//EventSubscribe 订阅
			case message.EventSubscribe:
				text := message.NewText("《近日趣事》感谢您的关注：\n  ※点+号发送位置获取天气提醒")
				return &message.Reply{message.MsgTypeText, text}
			default:
				text := message.NewText("点击+号发送位置获取天气提醒")
				return &message.Reply{message.MsgTypeText, text}
			}
		default:
			//回复消息：演示回复用户发送的消息
			text := message.NewText("点击+号发送位置获取天气提醒")
			return &message.Reply{message.MsgTypeText, text}
		}
	})

	//处理消息接收以及回复
	err := server.Serve()
	if err != nil {
		fmt.Println(err)
		return
	}

	//发送回复的消息
	server.Send()
	return
}

**Comment by silenceper** [comment]
ServeXML 里面是什么？

**Comment by nosix-me** [comment]
beego 框架定义的以xml的格式输出数据，这样用是不对的我认为，因为 wechat里边 server.send()已经发送完数据了

**Comment by nosix-me** [comment]
ServeXML这个是beego定义的以xml的方式输出结果，不过wechat中已经把结果返回，猜测beego处理流程中有其它处理导致的异常，
wechat可以通过server获取最后的返回结果然后由beego控制返回这样就容易结合了


原始邮件
发件人:silencepernotifications@github.com
收件人:silenceper/wechatwechat@noreply.github.com
抄送:nosixnosix.me@gmail.com; Authorauthor@noreply.github.com
发送时间:2017年8月8日(周二) 12:05
主题:Re: [silenceper/wechat] 结合beego 验证失败 http: wrote more than the declared Content-Length (#25)


ServeXML 里面是什么？

**Comment by silenceper** [comment]
把ServeXML()这个方法去掉就好了，因为这表示将ctx.Data中的内容以xml的方式输出，其实我已经自己返回结果了，导致的报错。

而且并不打算将内容抛出来由自己来框架来输出，因为这本身就是一个微信的封装，况且微信的返回值有的接口返回xml有的返回json或纯文本，外面维护代价有点高。所以目前先这样，没毛病~

**Comment by nosix-me** [comment]
去掉之后 beego会提示找不到 页面模板 **.tpl 目前处理的方式是在router层直接调用service 
   	beego.Post("/jrs/msg",service.Handle);

**Comment by silenceper** [comment]
应该取控制beego不输出  Controller struct中有一个EnableRender属性可以设置。

**Comment by nosix-me** [comment]
3Q 搞定了  对beego刚开始学  希望楼主在例子中给个beego工程的例子

**Comment by silenceper** [comment]
欢迎pr

**Comment by hoverZ** [comment]
若 wechat 是否被做了单例且范围为整个应用
其实出现并发时可能会造成这种情况

可以把 wechat 的单例范围缩小至 单个请求
