### ISSUE TITLE
一直期待你出开放平台的ｓｄｋ，终于等到了

### ISSUE THREAD

**Issue by yongge666** [silenceper/wechat#253]
## 问题及现象
<!-- 描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
感谢作者的付出，ｐｈｐ和ｊａｖａ生态的微信ｓｄｋ已经很丰富了，ｇｏ作为后起之秀，生态链薄弱，支持你，加油

**Comment by silenceper** [comment]
卖力码代码中 🦀 
开放平台在v2.0版本实现
