### ISSUE TITLE
菜单查询有bug, 结构体matchrule的group_id字段定义类型错了

### ISSUE THREAD

**Issue by 600ML** [silenceper/wechat#269]
//GetMenu 获取菜单配置
func (menu *Menu) GetMenu() (resMenu ResMenu, err error) {}
unmarshal报错

json: cannot unmarshal string into Go struct field MatchRule.conditionalmenu.matchrule.group_id of type int32

**Comment by 600ML** [comment]
接口返回是字符串
"matchrule": {
       "group_id": **"2"**
}

结构体定义
//MatchRule 个性化菜单规则
type MatchRule struct {
	GroupID            **int32**  `json:"group_id,omitempty"`
	...
}

**Comment by silenceper** [comment]
多谢，欢迎提个pr，修复该问题。
