### ISSUE TITLE
开放平台如何获取component_verify_ticket

### ISSUE THREAD

**Issue by zhengpeiqiang** [silenceper/wechat#272]
## 问题及现象
<!-- 描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
![image](https://user-images.githubusercontent.com/37537489/83389251-7d860580-a422-11ea-99ad-5e341c5cbde0.png)
这个appid应该是没有的，在一开始。。。

**Comment by silenceper** [comment]
1、component_verify_ticket 是通过事件推送获取到，所以通过SetMessageHandler设置get/set ticket
类似如下：
```go
// 传入request和responseWriter
server := officialAccount.GetServer(req, rw)
//设置接收消息的处理方法
server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {
    if msg.InfoType == message.InfoTypeVerifyTicket {
        componentVerifyTicket, err := openPlatform.SetComponentAccessToken(msg.ComponentVerifyTicket)
        if err != nil {
            log.Println(err)
            return nil
        }
        //debug 
        //fmt.Println(componentVerifyTicket)
        rw.Write([]byte("success"))
        return nil
    }
    //handle other message
    //
    
    
    return nil
```

**Comment by zhengpeiqiang** [comment]
![image](https://user-images.githubusercontent.com/37537489/83588899-f604d780-a584-11ea-932a-4e4c5c0a1a5f.png)
这个如果是开放平台的话，一开始是没有公众号授权的，这句
appID := "xxx"
officialAccount := openPlatform.GetOfficialAccount(appID) 
感觉有点问题

**Comment by silenceper** [comment]
这里确实有问题，要将GetServer要拆开来

**Comment by silenceper** [comment]
参考这个分支的提交
https://github.com/silenceper/wechat/tree/feature-v2/openplatform

![image](https://user-images.githubusercontent.com/2044558/83591027-9a891880-a589-11ea-9341-97f414093bd6.png)



<blockquote><img src="https://avatars0.githubusercontent.com/u/2044558?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>
