### ISSUE TITLE
v2缺少公众号账号管理

### ISSUE THREAD

**Issue by PowerDos** [silenceper/wechat#276]
可以开个分支，有必要的话，我可以提供代码贡献
![image](https://user-images.githubusercontent.com/19368599/84098676-753d5400-aa3a-11ea-8898-99f8c523e6a9.png)

**Comment by silenceper** [comment]
二维码的实现在这里：https://github.com/silenceper/wechat/blob/release-2.0/officialaccount/basic/qr.go
> 文档缺失

生成短连接的这个没实现，你可以建一个url的目录，在里面实现该功能。 

提交pr就可以了，不用在这里新建分支。

<blockquote><img src="https://avatars0.githubusercontent.com/u/2044558?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>
