### ISSUE TITLE
小程序客户端缺少订阅消息服务

### ISSUE THREAD

**Issue by holdno** [silenceper/wechat#281]
## 问题及现象
小程序客户端实例化后缺少获取订阅消息服务的方法，应该是漏了吧
release-2.0 和最新的tag貌似没有保持一致

**Comment by holdno** [comment]
版本问题...

**Comment by holdno** [comment]
release-2.0 和最新的tag貌似没有保持一致

**Comment by silenceper** [comment]
目前尽量维持每个月发布一个tag。
如果用最新的可以通过go module直接指定 @release-2.0分支

**Comment by holdno** [comment]
release-2.0跟tag v2.0 从理解上应保持一致哈
