### ISSUE TITLE
微信回调signType为空的问题

### ISSUE THREAD

**Issue by avtion** [silenceper/wechat#282]
# 产生问题的代码  
https://github.com/silenceper/wechat/blob/c14c020a3cd892926e3fdc8879d52ada9c899505/pay/notify/paid.go#L89-L96

https://github.com/silenceper/wechat/blob/c14c020a3cd892926e3fdc8879d52ada9c899505/util/crypto.go#L201-L205

# 产生问题的原因  
如果微信回调没有携带`SignType`会使`signType`变量为空，从而影响到`CalculateSign`参数，最终导致原本默认为`md5`加密的方式变成了默认为`sha256`加密方式

> [微信支付开发文档](https://pay.weixin.qq.com/wiki/doc/api/external/jsapi.php?chapter=9_7)
> 支付结果通知 --> sign_type（非必填） ---> 签名类型，目前支持HMAC-SHA256和MD5，默认为MD5

# 修复方法
修改判断条件

**Comment by silenceper** [comment]
多谢反馈，并修复
