### ISSUE TITLE
release2.0 wechat/pay/pay.go 服务项不全

### ISSUE THREAD

**Issue by holdno** [silenceper/wechat#285]
## 问题及现象
release2.0分支中 微信支付服务(NewPay)貌似只能导出 order 和 notify  
缺少 pay refund等，我看代码已经是有了

**Comment by silenceper** [comment]
缺少一个refund

**Comment by silenceper** [comment]
fix in #286

**Comment by holdno** [comment]
refund功能中 ca只能通过传入文件路径来获取... 缺乏灵活性
希望可以支持自定义加载证书的能力
