### ISSUE TITLE
这段代码，c.Request c.Writer从哪里来的呢？有没有完整代码呢？

### ISSUE THREAD

**Issue by edl7878** [silenceper/wechat#29]
以下是一个创建二级菜单的例子

mu := wc.GetMenu(c.Request, c.Writer)

buttons := make([]*menu.Button, 1)
btn := new(menu.Button)

//创建click类型菜单
btn.SetClickButton("name", "key123")
buttons[0] = btn

//设置btn为二级菜单
btn2 := new(menu.Button)
btn2.SetSubButton("subButton", buttons)

buttons2 := make([]*menu.Button, 1)
buttons2[0] = btn2

//发送请求
err := mu.SetMenu(buttons2)
if err != nil {
	fmt.Printf("err= %v", err)
	return
}

**Comment by edl7878** [comment]
能回复一下么？如何获得已有菜单配置，修改之，传回微信，以及响应click，发送文本消息，这个流程还是没搞明白哦。menu完全不会用，有代码例子就好了，多谢哦。

**Comment by silenceper** [comment]
其实就是 request和responseWriter  对象。

其余的问题先把微信的文档看完吧，回过来就知道了。
