### ISSUE TITLE
公众号默认菜单添加已失效

### ISSUE THREAD

**Issue by Xuzan9396** [silenceper/wechat#294]
## 提示  40016 | 不合法的按钮个数
![image](https://user-images.githubusercontent.com/24741439/86730052-b720e080-c060-11ea-91f2-2965933baa13.png)

## 发送的数据 （自己组装的http 函数可以发， 内置的包无效报错）
```
{
    "button":[
        {
            "name":"直播1",
            "sub_button":[
                {
                    "type":"click",
                    "name":"下载地址",
                    "key":"download"
                }
            ]
        },
        {
            "name":"联系我们",
            "sub_button":[
                {
                    "type":"click",
                    "name":"运营客服",
                    "key":"kefu"
                }
            ]
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/24741439/86730803-7c6b7800-c061-11ea-9622-8c675fc30cdc.png)

**Comment by silenceper** [comment]
sdk没做啥特殊的。

你把json放在 https://mp.weixin.qq.com/debug/ 试一下？ 


<blockquote><img src="/debug/zh_CN/htmledition/images/icon/common/favicon20f79b.ico" width="48" align="right"><div><strong><a href="https://mp.weixin.qq.com/debug/">微信公众平台接口调试工具</a></strong></div></blockquote>

**Comment by Xuzan9396** [comment]
@silenceper   微信的工具是没问题的， 就是原生的json, 放到go 里面调用就不行
![image](https://user-images.githubusercontent.com/24741439/86889938-249b4280-c12f-11ea-816a-029e5ab608ec.png)

现在只能自己封装http 去发送，先这样吧， 不知道你们遇到没

**Comment by Xuzan9396** [comment]
@silenceper  

还一个集成的redis  里面的Do 方法能不能放出来， 现在不能使用redis 其他命令

**Comment by silenceper** [comment]
你项目中用到的redis 命令，建议自己建一个client

**Comment by Xuzan9396** [comment]
批量获取永久素材能获取素材，但是err 不为nil 
接口 BatchGetMaterial(permanentMaterialType PermanentMaterialType, offset, count int64)
err 为  commonError is invalid or not struct
@silenceper

**Comment by silenceper** [comment]
> 批量获取永久素材能获取素材，但是err 不为nil
> 接口 BatchGetMaterial(permanentMaterialType PermanentMaterialType, offset, count int64)
> err 为 commonError is invalid or not struct
> @silenceper

fix in #303

**Comment by sunjun** [comment]
util/http.go里面
 ```
 func PostJSON(uri string, obj interface{}) ([]byte, error) {
	  jsonData, err := json.Marshal(obj)
	  if err != nil {
		  return nil, err
	  }
	  jsonData = bytes.ReplaceAll(jsonData, []byte("\\u003c"), []byte("<"))
	  jsonData = bytes.ReplaceAll(jsonData, []byte("\\u003e"), []byte(">"))
	  jsonData = bytes.ReplaceAll(jsonData, []byte("\\u0026"), []byte("&"))
	  body := bytes.NewBuffer(jsonData)
	  response, err := http.Post(uri, "application/json;charset=utf-8", body)
	  if err != nil {
		  return nil, err
	  }
	  defer response.Body.Close()
  
	  if response.StatusCode != http.StatusOK {
		  return nil, fmt.Errorf("http get error : uri=%v , statusCode=%v", uri, response.StatusCode)
	  }
	  return ioutil.ReadAll(response.Body)
  }
```

需要改为
 ```
 func PostJSON(uri string, jsonString string) ([]byte, error) {
	  body := bytes.NewBuffer([]byte(jsonString))
	  response, err := http.Post(uri, "application/json;charset=utf-8", body)
	  if err != nil {
		  return nil, err
	  }
	  defer response.Body.Close()
  
	  if response.StatusCode != http.StatusOK {
		  return nil, fmt.Errorf("http get error : uri=%v , statusCode=%v", uri, response.StatusCode)
	  }
	  return ioutil.ReadAll(response.Body)
  }
```

**Comment by silenceper** [comment]
already fixed in #353
