### ISSUE TITLE
打算支持企业微信吗？

### ISSUE THREAD

**Issue by wutongci** [silenceper/wechat#304]
## 问题及现象
<!-- 描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
你好请问一下支持企业微信么？如果不支持的话，打算fork 一个开发了

**Comment by amorist** [comment]
我看已经在计划中了
![image](https://user-images.githubusercontent.com/14037268/87111219-61844800-c29b-11ea-8ba9-86ffaec8d09b.png)

**Comment by yongge666** [comment]
已打赏，支持！！！

**Comment by silenceper** [comment]
在 #398 中讨论
