### ISSUE TITLE
关于忽略回复的问题

### ISSUE THREAD

**Issue by zacharyhli** [silenceper/wechat#309]
## 问题及现象
- 通过sdk实现当用户发送某个关键词时不作回复。微信官方文档写直接回复"success"或者""空串(ps: 不是将XML结构中的content字段内容置为"success"或"")。当我这么设置时，提示"不支持的回复消息"。
- 看了下代码，是因为有这步判断，如下图server.go中：
![image](https://user-images.githubusercontent.com/25129109/89169150-6e513e80-d5b0-11ea-8135-09a83412a84d.png)
导致不通过

**Comment by narrowizard** [comment]
```go
server := officialAccount.GetServer(req, rw)
server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {
        // 直接使用ResponseWriter写入"success"
        rw.Write([]byte("success"))
        // 返回nil表明不回复消息
        return nil
})
err := server.Serve()
if err != nil {
    fmt.Println(err)
    return
}
server.Send()
```

**Comment by zacharyhli** [comment]
> ```go
> server := officialAccount.GetServer(req, rw)
> server.SetMessageHandler(func(msg message.MixMessage) *message.Reply {
>         // 直接使用ResponseWriter写入"success"
>         rw.Write([]byte("success"))
>         // 返回nil表明不回复消息
>         return nil
> })
> err := server.Serve()
> if err != nil {
>     fmt.Println(err)
>     return
> }
> server.Send()
> ```

但是我的需求是在自定义的handle函数里面，对某些关键词忽略回复。这个时候你的方法好像就不行了

**Comment by narrowizard** [comment]
@Lee-johnH 能否提供demo呢

**Comment by zacharyhli** [comment]
@narrowizard 解决了...直接在handle函数里面返回nil就可以了

**Comment by zacharyhli** [comment]
@narrowizard 你说得对 直接返回nil就表明不回复消息了。 也不用写入"success". THX
