### ISSUE TITLE
开放平台获取JSSDK需要的配置参数【缓存Key错误的使用了开放平台的APPID】

### ISSUE THREAD

**Issue by anden007** [silenceper/wechat#329]
此问题造成开放平台授权的多个公众号公用一个Ticket，造成微信分享不正常！
目前我的处理方式是手动调用NewDefaultJsTicket方法初始化一个使用正确AppID的处理方法，然后再调用SetJsTicketHandle注入，但此BUG还是希望作者帮忙处理，实在是太隐蔽了，花了好久才发现问题。
js初始化方法：
`officialAccount := m.Component.OpenPlatform.Platform.GetOfficialAccount(appId)
js := officialAccount.PlatformJs()`

js组件实例化过程：

`func NewJs(context *context.Context) *Js {
	js := new(Js)
	js.Context = context
	jsTicketHandle := credential.NewDefaultJsTicket(context.AppID, credential.CacheKeyOfficialAccountPrefix, context.Cache)
	js.SetJsTicketHandle(jsTicketHandle)
	return js
}`

问题分析：
GetOfficialAccount传入的appId为私有变量，而NewJs中调用credential.NewDefaultJsTicket时使用了context.AppID，此AppID为开放平台的AppID，并非GetOfficialAccount传入的appId，虽然在调用GetConfig方法时需要传入公众号的appId，但缓存jsTicket时使用了错误的context.AppID（开放平台的）。

**Comment by silenceper** [comment]
ref: #302

@narrowizard 是否有兴趣修正此问题?

**Comment by narrowizard** [comment]
ok, 我抽空看一下这个问题

**Comment by narrowizard** [comment]
已经提交pr， 麻烦 @anden007 测试一下

**Comment by anden007** [comment]
> 已经提交pr， 麻烦 @anden007 测试一下

高效！我测试一下

**Comment by silenceper** [comment]
@anden007  请问，验证如何？

**Comment by anden007** [comment]
> @anden007 请问，验证如何？

可以了！！
