### ISSUE TITLE
开发平台实例化公众号的时候 传入的appid是开发平台的appid

### ISSUE THREAD

**Issue by 1307super** [silenceper/wechat#333]
在开放平台实例化公众号的时候 给公众号的config传入的是开发平台的appId, 所以造成了混淆:
![image](https://user-images.githubusercontent.com/35326304/96216416-d52ca400-0fb2-11eb-8f63-e5502a8183e7.png)
![image](https://user-images.githubusercontent.com/35326304/96216681-7156ab00-0fb3-11eb-827a-f3ab442fcd61.png)

代授权接口处,从接口传入了公众号appid, 又获取了oauth的appid 这里的oauth appid由于上面实例化时传的开放平台的appid 所以没问题
![image](https://user-images.githubusercontent.com/35326304/96216824-d1e5e800-0fb3-11eb-911d-2c941dafe0fe.png)
在获取jssdk的时候就出现问题了: 传入的ctx.appid是开发平台的appid
![image](https://user-images.githubusercontent.com/35326304/96216875-ec1fc600-0fb3-11eb-8454-ea059094c23e.png)

设计应该没问题 主要是容易混淆;  这个坑有点深, 很容易将config的appid当成是公众号的appid使用

**Comment by silenceper** [comment]
在这里修复 #331
