### ISSUE TITLE
关于token失效不能及时刷新的问题

### ISSUE THREAD

**Issue by jindai0305** [silenceper/wechat#336]
## 在新token获取以后 缓存好的token并没有失效 即使是在调用微信返回了40001后
测试服与正式服的token并不是存在同一个池子里 所以会被反复刷新 然后就会经常得到
![image](https://user-images.githubusercontent.com/24999354/97132120-f777ac00-1780-11eb-9ac0-7af9539c2dd2.png)
查看获取token的代码
 ```go
        accessTokenCacheKey := fmt.Sprintf("%s_access_token_%s", ak.cacheKeyPrefix, ak.appID)
	val := ak.cache.Get(accessTokenCacheKey)
	if val != nil {
		accessToken = val.(string)
		return
	}

	//cache失效，从微信服务器获取
	var resAccessToken ResAccessToken
	resAccessToken, err = GetTokenFromServer(ak.appID, ak.appSecret)
	if err != nil {
		return
	}
        expires := resAccessToken.ExpiresIn - 1500
	err = ak.cache.Set(accessTokenCacheKey, resAccessToken.AccessToken, time.Duration(expires)*time.Second)
 ```
调用的代码
```go
var accessToken string
accessToken, err = qrCode.GetAccessToken()
if err != nil {
	return
}
urlStr = fmt.Sprintf(urlStr, accessToken)
var contentType string
response, contentType, err = util.PostJSONWithRespContentType(urlStr, body)
```
由于token是附加到url中然后再去调用，所以在实际调用处并不能拿到wechat的实例。且cache是私有变量，实际上在其他地方也不能调取这个方法。

目前这边的解决方法是：重写了获取token的方法，在返回token前调用了微信的没有调用次数限制的接口，如果返回了40001，则让当前token缓存失效并缓存最新的token。但是这个做法实际上是有点蠢的。

我的期望是
1.如果在调用微信接口时返回了 40001 能够自动刷新缓存并能自动重试调用对应接口（最优）
```go
var accessToken string
var contentType string
for i := 2; i > 0; i-- {
	accessToken, err = qrCode.GetAccessToken()
	if err != nil {
		return
	}
	urlStr = fmt.Sprintf(urlStr, accessToken)
	response, contentType, err = util.PostJSONWithRespContentType(urlStr, body)
	if err.ErrCode == 40001 {
		// 刷新缓存
		continue
	}
}
```
2.将cache设置为外部可访问或者在
```go
type AccessTokenHandle interface {
	GetAccessToken() (accessToken string, err error)
}
```
处添加一个RefreshAccessToken或CheckAccessTokenInvalid方法。目前好像只能设置GetAccessToken方法

谢谢~

**Comment by silenceper** [comment]
首先你的token没有共用，这里不合理，因为很可能两边刷新导致次数被调用光。

建议通过这个方法：https://github.com/silenceper/wechat/blob/4c35924b8cb121e3047fd48c28577a803c6ea24d/officialaccount/officialaccount.go#L39

进行自定义token的管理，把token集中管理起来。

**Comment by jindai0305** [comment]
haode

**Comment by chenyu1990** [comment]
我用了redis，仍然会有40001错误。

**Comment by ccfish86** [comment]
如果可以使用 稳定版接口调用凭据【getStableAccessToken】会好一些
