### ISSUE TITLE
使用了wechat的小程序调用云开发，在触发云函数后，无法正确获得resp_data

### ISSUE THREAD

**Issue by littletow** [silenceper/wechat#337]
## 问题及现象
使用了wechat的小程序调用云开发，在触发云函数后，无法正确获得resp_data

代码片段如下：
obj := fmt.Sprintf(`{"title":"%s","tag":"%s","fileid":"%s","openid":"%s"}`, title, tag, fileid, openid)
res, err := wcTcb.InvokeCloudFunction(cloudEnv, "uploadArticle", obj)
调用之后的结果，打印res获得
&{{0 ok} null}
现在明显resp_data为空，但是我的云函数是有返回值的。云函数在小程序中使用是正常的
不知道哪里的问题

**Comment by silenceper** [comment]
在小程序管理界面看下 函数执行的log.

或者你拿到`access_token` 手动调用下，看下结果
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-http-api/functions/invokeCloudFunction.html

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-http-api/functions/invokeCloudFunction.html">invokeCloudFunction | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by littletow** [comment]
非常感谢您的回答，根据您的提示，我已经找到原因。这是由于我的原因导致的。小程序的云函数返回的结果有问题造成。
