### ISSUE TITLE
v2 跟 v1有啥区别

### ISSUE THREAD

**Issue by rebider** [silenceper/wechat#342]

**Comment by silenceper** [comment]
v1项目 最开始只是针对公众号去设计，后面随着api逐渐完善 整个package 的已经有点乱了。

所以新增了v2

**Comment by rebider** [comment]
我能不能直接v1升级到v2，改动大不？ 大部分项目都用到了10个以上微信api

**Comment by silenceper** [comment]
v1是可以继续用的， 只是会相对滞后
