### ISSUE TITLE
公众号网页授权后获取用户基本信息支持语言入参

### ISSUE THREAD

**Issue by chekun** [silenceper/wechat#344]
目前2.0中，授权后获取用户基本信息代码中写死了 `lang=zh_CN`

```
userInfoURL            = "https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN"
```

[点我看代码](https://github.com/silenceper/wechat/blob/release-2.0/officialaccount/oauth/oauth.go#L18
)

需要将其参数化

**Comment by chekun** [comment]
#345 已提交Pull Request

**Comment by chenyu1990** [comment]
函数定义改成  langs ...string
代码
var lang string
if len(langs) > 0 {
    lang = langs[0]
}
