### ISSUE TITLE
创建微信微信菜单47001

### ISSUE THREAD

**Issue by 913512417** [silenceper/wechat#352]
![image](https://user-images.githubusercontent.com/23518931/103077487-cd205e80-460a-11eb-98c6-42a0162ef185.png)
![image](https://user-images.githubusercontent.com/23518931/103077510-da3d4d80-460a-11eb-9888-c369f2023901.png)

**Comment by silenceper** [comment]
@913512417 已提交pr修复，可以验证下。

另外SetMenu 方法我这边验证是正常的

**Comment by xdkaka** [comment]
这个可以跑成功？看源代码对string进行json.Marshal
