### ISSUE TITLE
可以发布新版本的go package吗？

### ISSUE THREAD

**Issue by mscb402** [silenceper/wechat#366]
现在从go pkg拉取到的都是 v2.0.4 版本的代码，是 Oct 24, 2020 发布的，距今已经好几个月。
2.0.4版本有部分代码有bug，现在GitHub上新的代码修复了这些bug。
所以可以把当前的新代码发布个新的小版本吗？

**Comment by silenceper** [comment]
先已发布 v2.0.5-rc.1 版本，待稳定一段时间后，再release

**Comment by mscb402** [comment]
谢谢呀～
