### ISSUE TITLE
access_token缓存命名规则配置

### ISSUE THREAD

**Issue by LonelySally** [silenceper/wechat#374]
在多个项目里要共用`access_token`,能否支持自定义access_token缓存key.现在是根据cacheKeyPrefix+_access_token_文本+appID的形式写死在项目内.
增加一个方法SetAccessTokenCacheKey或者配置以此来达到覆盖缓存key名称.

**Comment by silenceper** [comment]
微信公众号可以使用该方法，自定义ak的设置方式
https://github.com/silenceper/wechat/blob/05059694392c9e0e6b2fd089e1e9c5a5414cf236/officialaccount/officialaccount.go#L39

**Comment by LonelySally** [comment]
> 微信公众号可以使用该方法，自定义ak的设置方式
> https://github.com/silenceper/wechat/blob/05059694392c9e0e6b2fd089e1e9c5a5414cf236/officialaccount/officialaccount.go#L39

`AccessTokenHandle interface`接口内没有实现`SetAccessToken`.实际修改key需要的是Set方法,相应的需要对应的Get方法去获取.
另外能不能提供一个手动刷新access_token的接口?在操作时经常性发生errcode40001.
```golang
var (
	official *officialaccount.OfficialAccount
)
func init() {
	//memory := cache.NewMemory()
	cfg := &offConfig.Config{
		AppID:     g.Config().GetString("wechat.AppID"),
		AppSecret: g.Config().GetString("wechat.AppSecret"),
		Token:     g.Config().GetString("wechat.Token"),
		Cache: cache.NewRedis(&cache.RedisOpts{
			Host:        g.Config().GetString("redis.wechat.host"),
			Password:    g.Config().GetString("redis.wechat.password"),
			Database:    g.Config().GetInt("redis.wechat.database"),
			MaxIdle:     2,
			MaxActive:   6,
			IdleTimeout: 60,
		}),
	}
	official = officialaccount.NewOfficialAccount(cfg)
}
func Send(msg message.TemplateMessage){
//useSend回执结果经常返回errcode40001.
//template msg send error : errcode=40001 , errmsg=invalid credential, access_token is invalid or not latest rid: 
official.GetTemplate().Send(&msg)
}

```

**Comment by LonelySally** [comment]
> > 微信公众号可以使用该方法，自定义ak的设置方式
> > https://github.com/silenceper/wechat/blob/05059694392c9e0e6b2fd089e1e9c5a5414cf236/officialaccount/officialaccount.go#L39
> 
> `AccessTokenHandle interface`接口内没有实现`SetAccessToken`.实际修改key需要的是Set方法(虽然可以定义cacheKeyPrefix,但是_access_token这部分被写死在代码中了).
> 另外能不能提供一个手动刷新access_token的接口?

**Comment by silenceper** [comment]
`AccessTokenHandle interface`中提供的是GetAK的方法，ak的获取完全由自己来实现（自己调用ak获取接口以及自己用何种方式存储，都是由自己来选择），你可以看下default的实现：https://github.com/silenceper/wechat/blob/05059694392c9e0e6b2fd089e1e9c5a5414cf236/credential/default_access_token.go




<blockquote><img src="https://avatars.githubusercontent.com/u/2044558?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>

**Comment by LonelySally** [comment]
> `AccessTokenHandle interface`中提供的是GetAK的方法，ak的获取完全由自己来实现（自己调用ak获取接口以及自己用何种方式存储，都是由自己来选择），你可以看下default的实现：https://github.com/silenceper/wechat/blob/05059694392c9e0e6b2fd089e1e9c5a5414cf236/credential/default_access_token.go
> 
> > <img alt="" width="48" src="https://avatars.githubusercontent.com/u/2044558?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[silenceper/wechat](https://github.com/silenceper/wechat)**WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.

懂了.`GetTokenFromServer`方法没注意到.我看到 `GetAccessToken()`就想当然的用`*AccessToken*`的方式找对应操作方法了..

<blockquote><img src="https://avatars.githubusercontent.com/u/2044558?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>
