### ISSUE TITLE
H5 微信支付的唤起支持

### ISSUE THREAD

**Issue by airylinus** [silenceper/wechat#38]
according wechat doc:  https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1

唤起微信支付需要 **prepay_id** 参数，改参数需要服务器端调用接口生成。

**Comment by airylinus** [comment]
我在开发测试中，稍后会提 PR 求 review

**Comment by silenceper** [comment]
👍  期待

**Comment by cnsd365** [comment]
期待too
