### ISSUE TITLE
微信小程序订阅消息，无法修改参数类型

### ISSUE THREAD

**Issue by rayson-x** [silenceper/wechat#384]
推送小程序订阅消息时，微信进行了严格的参数验证，不符合类型的参数无法推送，现在的 subscribe.DataItem 只允许使用string类型，导致无法推送使用了number类型的模板

![image](https://user-images.githubusercontent.com/17398068/112815860-571d0f00-90b3-11eb-96d9-5b9f1790fb94.png)

![image](https://user-images.githubusercontent.com/17398068/112815469-ef66c400-90b2-11eb-9e17-fa401f7c2cb6.png)

**Comment by silenceper** [comment]
@sssxxxzzz  你好，感谢你反馈这个问题。
我在#390 中修复了该问题，麻烦确认下。
