### ISSUE TITLE
文档是不是挂了，打不开了

### ISSUE THREAD

**Issue by xjqxz2** [silenceper/wechat#399]
## 问题及现象
<!-- 描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by silenceper** [comment]
我这边正常呢，你看下返回什么错误码

**Comment by silenceper** [comment]
文档无法访问，可以先直接进入这个文档仓库进行查看  https://github.com/gowechat/docs

<blockquote><img src="https://opengraph.githubassets.com/47c9b04b932fac4259d175460b3fda34686ee445cec4bd5fbd59efc219da68dc/gowechat/docs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/gowechat/docs">gowechat/docs</a></strong></div><div>【文档】微信开发SDK(Wechat SDK for Golang) . Contribute to gowechat/docs development by creating an account on GitHub.</div></blockquote>

**Comment by silenceper** [comment]
换了个服务器，现在可以访问了
