### ISSUE TITLE
微信支付回调 优惠券金额CouponFeed0 CouponFeed1 CouponFeed2字段映射失败

### ISSUE THREAD

**Issue by my-future** [silenceper/wechat#417]
当使用优惠券时，CouponFeed0，CouponFeed1，CouponFeed2这三个字段映射失败
![image](https://user-images.githubusercontent.com/19463197/125600900-9ab8f6cc-5203-4946-ac3b-8ebd591ec38c.png)
原因: 
![image](https://user-images.githubusercontent.com/19463197/125601497-8452d9d0-4420-4fd3-9d07-71f888e9d4fd.png)
转换出错
临时解决方法:
![image](https://user-images.githubusercontent.com/19463197/125601648-855b57dd-91c7-4afd-aff7-25f1f6a13766.png)
将这三个字段更改，但是这样破坏性较大

**Comment by silenceper** [comment]
这个是什么问题？ `structs.Map` 没有映射成功？

**Comment by my-future** [comment]
是的structs.Map CouponFeed0，CouponFeed1，CouponFeed2这三个字段 映射不了
微信发来的xml为coupon_fee_0
`<xml>
  <appid><![CDATA[111111]]></appid>
  <bank_type><![CDATA[BOC_DEBIT]]></bank_type>
  <cash_fee><![CDATA[490]]></cash_fee>
  <coupon_count><![CDATA[1]]></coupon_count>
  <coupon_fee>500</coupon_fee>
  <coupon_fee_0><![CDATA[500]]></coupon_fee_0>
  <coupon_id_0><![CDATA[11111]]></coupon_id_0>
  <fee_type><![CDATA[CNY]]></fee_type>
  <is_subscribe><![CDATA[N]]></is_subscribe>
  <mch_id><![CDATA[aaaaaa]]></mch_id>
  <nonce_str><![CDATA[2132221]]></nonce_str>
  <openid><![CDATA[aaaaaa]]></openid>
  <out_trade_no><![CDATA[11111]]></out_trade_no>
  <result_code><![CDATA[SUCCESS]]></result_code>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <sign><![CDATA[dsad]]></sign>
  <time_end><![CDATA[20210714140315]]></time_end>
  <total_fee>990</total_fee>
  <trade_type><![CDATA[JSAPI]]></trade_type>
  <transaction_id><![CDATA[11111]]></transaction_id>
</xml>
`
上面的值我已经替换，你可以试试

**Comment by silenceper** [comment]
我没看出来，是什么原因导致映射不了？ 另外你说的临时解决办法更改是更改成什么。

**Comment by silenceper** [comment]
@quxiaolong1504  可以帮确认下？
