### ISSUE TITLE
获取access Token时报无效指针？

### ISSUE THREAD

**Issue by zxing2004** [silenceper/wechat#42]
代码如下：
func WechatConfig() {
	appid := beego.AppConfig.String("appid")
	appsecret := beego.AppConfig.String("appsecret")
	config := &wechat.Config{
		AppID:          appid,
		AppSecret:      appsecret,
		Token:          beego.AppConfig.String("token"),
		EncodingAESKey: beego.AppConfig.String("encodingAESKey"),
	}
	wc := wechat.NewWechat(config)
	fmt.Println(wc.GetAccessToken())
}

在使用wc.GetAccessToken就出现：

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x81e58e]

goroutine 1 [running]:
github.com/silenceper/wechat/context.(*Context).GetAccessToken(0xc0420fa080, 0x0, 0x0, 0x0, 0x0)
        D:/gowork/src/github.com/silenceper/wechat/context/access_token.go:36 +0x13e
github.com/silenceper/wechat.(*Wechat).GetAccessToken(0xc04206bec0, 0xc0421490e0, 0x9, 0xc04204eb00, 0x20)
        D:/gowork/src/github.com/silenceper/wechat/wechat.go:58 +0x35
cdbcb/models.WechatConfig()
        D:/gowork/src/cdbcb/models/wechat.go:20 +0x27a
main.main()
        D:/gowork/src/cdbcb/main.go:11 +0x29

目前不知道是哪个位置出现了无效指针

**Comment by silenceper** [comment]
你没有设置cache。[#L36](https://github.com/silenceper/wechat/blob/master/context/access_token.go#L36)

**Comment by zxing2004** [comment]
已经发现了😥，还是谢谢你
