### ISSUE TITLE
TemplateMessage下Color的json转义关键字

### ISSUE THREAD

**Issue by LonelySally** [silenceper/wechat#421]
模板消息
~~~
//TemplateMessage 发送的模板消息内容
type TemplateMessage struct {
	ToUser     string                       `json:"touser"`          // 必须, 接受者OpenID
	TemplateID string                       `json:"template_id"`     // 必须, 模版ID
	URL        string                       `json:"url,omitempty"`   // 可选, 用户点击后跳转的URL, 该URL必须处于开发者在公众平台网站中设置的域中
	Color      string                       `json:"color,omitempty"` // 可选, 整个消息的颜色, 可以不设置 
	Data       map[string]*TemplateDataItem `json:"data"`            // 必须, 模板数据

	MiniProgram struct {
		AppID    string `json:"appid"`    //所需跳转到的小程序appid（该小程序appid必须与发模板消息的公众号是绑定关联关系）
		PagePath string `json:"pagepath"` //所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar）
	} `json:"miniprogram"` //可选,跳转至小程序地址
}
~~~
Color      string                       `json:"color,omitempty"` 这个json-tag是不是错了,应该是topcolor.
![image](https://user-images.githubusercontent.com/26945597/126733772-3c163849-e8a2-4cb0-8e5e-20882a80c76e.png)

**Comment by silenceper** [comment]
你是从哪里看到这个topcolor字段，你可以搜一下，这个可能是已废除的字段

**Comment by LonelySally** [comment]
> topcolor

微信模板消息那边找到的.因为有需求设置first的颜色然后就设置了Item下的color

~~~
map[string]*message.TemplateDataItem{
				"first": {
					Value: "first",
					Color: "#ff0000",//不生效
				},
				"remark": {
					Value: "remake",
					Color: "#ff0000",
				},
				"keyword1": {
					Value: "key1",
					Color: "#1b1b1b",
				},
				"keyword2": {
					Value: "key2",
					Color: "#1b1b1b",
				},
				"keyword3": {
					Value: "key3",
					Color: "#1b1b1b",
				},
			}

message.TemplateMessage{
		ToUser:     openid,
		TemplateID: templateId,
		URL:        "",
		Color:      "#ff0000",//也同样不生效
		Data:       data,
	}
~~~

设置成以上颜色样式后发现发送出去的除了first其它的颜色全部生效了.然后尝试设置TemplateMessage下的Color为"#ff0000"也没有使first变为红色.然后在官方的文档里看到了这个topcolor跟TemplateMessage的Color的jsontag对应不上,不知道是哪边的问题[捂脸]

**Comment by silenceper** [comment]
文档地址发一下

**Comment by LonelySally** [comment]
> 文档地址发一下

已经破案了https://developers.weixin.qq.com/community/develop/doc/0004a28f8e4e406414f97cf755b400?_at=1588344208033 坑b tx下了这个功能页不在模板消息文档那边说明.如果可以的话在方法注释上描述下这个color不会对first生效,防止后面的人继续进坑.感谢回复.

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/wechat_search_common_assets/res/developers/3x/developers-db8b687441.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/community/develop/doc/0004a28f8e4e406414f97cf755b400?_at=1588344208033">微信公众号消息first对象颜色无效,是因为first不支持颜色显示吗? | 微信开放社区</a></strong></div><div>{"touser":"xxxx","mp_template_msg":{"appid":"xxxx","template_id":"xxxxxxxxxxxxxxxxxx","url":"","miniprogram":{"appid":"xxxxxxxx","pagepath":"xxxxxxxx/pages/enter/index?e=DEV&amp;act_id=1002"},"data":{"first":{"value":"您好，您的礼品福利已送达可直接领取\r\n","color":"#38a838"},"keyword1":{"value":"云票儿专属福利礼品\r\n","color":""},"keyword2":{"value":"2020年02月21日\r\n","color":""},"keyword3":{"value":"","color":""},"remark":{"value":"Champion新年专享，车主大礼包，0元领全棉时代29.9出行礼包，加油宝200元礼包，安踏100元优惠券!","color":"#38a838"}}}}本来设置颜色为 #38a838 实际效果显灰搜索相关问题是有人说到PC不支持 "first"标签，我这边使用的是手机端微信</div></blockquote>
