### ISSUE TITLE
[BUG]解密用户信息失败

### ISSUE THREAD

**Issue by rankingcong** [silenceper/wechat#430]
**描述**
解密用户授权信息：github.com/silenceper/wechat/v2@v2.0.6/miniprogram/encryptor/encryptor.go:71 报错

**关联日志信息**
invalid padding on input

**使用的版本**
 - SDK版本: v2.0.6

**Comment by rankingcong** [comment]
是 session_key 没有及时更新的问题 😅

**Comment by akazwz** [comment]
> 是 session_key 没有及时更新的问题 😅

请问是怎么解决的
