### ISSUE TITLE
[BUG]SetMenuByJSON调用报错

### ISSUE THREAD

**Issue by WongGinZoeng** [silenceper/wechat#434]
**描述**
调用此接口会报类似“SetMenu Error , errcode=47001 , errmsg=data format error rid: 61161631-13660caa-440611ee”错误。感觉应该是因为PostJSON方法里面对obj参数进行json.Marshal，但是由于传进去的是string，经过marshal，原本的json数据就有问题了。

**如何复现**
步骤：
1、
2、

**关联日志信息**

**使用的版本**
 - SDK版本: [比如 v0.0.0]

**Comment by silenceper** [comment]
可以debug一下，看下marshal之后最终提交的数据是什么样子的？

**Comment by silenceper** [comment]
@WongGinZoeng 问题是否解决，我先关闭了，如果有问题再反馈。
