### ISSUE TITLE
[咨询]微信退款没有RootCa证书（微信只提供apiclient_cert.p12、apiclient_cert.pem、apiclient_key.pem三个证书）

### ISSUE THREAD

**Issue by zhtfirst** [silenceper/wechat#441]
微信退款没有RootCa证书（微信只提供apiclient_cert.p12、apiclient_cert.pem、apiclient_key.pem三个证书），在退款Refund方法中的RootCa填什么

**Comment by zhtfirst** [comment]
新版的没有RootCa证书，只需要填写apiclient_cert.p12的证书就行，是我理解错了还以为要把证书的内容传回去，只需要把证书的地址传进去

**Comment by LonelySally** [comment]
能否告知下refund.Params里的RootCa指向的是下载回来的哪个文件?
