### ISSUE TITLE
mac编译 linux 版本，v2.0.8 会报找不到 msgaudit.Client

### ISSUE THREAD

**Issue by aassaadd** [silenceper/wechat#455]
mac 下使用 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -installsuffix cgo -o ./bin/linux/${appname} ./main.go 去编译项目 汇报错：
    silenceper/wechat/v2@v2.0.8/work/work.go:38:33: undefined: msgaudit.Client
查看源码应该是 linux 下使用c 的库吧，那块我在mac 下编译会报错
目前只能 使用2.0.4 版本 不会报错，

**Comment by silenceper** [comment]
@aassaadd  切换到v2.0.9-rc.1 版本可以。

这是因为企业微信会话存档 目前通过CGO方式实现。

**Comment by silenceper** [comment]
@aassaadd  是否还有问题？

**Comment by silenceper** [comment]
问题我先关闭了，如果有问题再反馈
