### ISSUE TITLE
[BUG]win环境下交叉编译linux,提示undefined: msgaudit.Client 和 undefined: msgaudit.NewClient

### ISSUE THREAD

**Issue by liect** [silenceper/wechat#459]
**描述**
undefined: msgaudit.Client 和 undefined: msgaudit.NewClient
**如何复现**
步骤：在Windows下开发,设置GOOS=linux之后,go build 去交叉编译
显示undefined: msgaudit.Client 和 undefined: msgaudit.NewClient
查看构建约束是在正确的,我接触Go时间不长,查了很多,还是无法解惑,遂提交这个lssue,期望得到您的解答.

**使用的版本**
 - SDK版本: 1.16 and 1.17

**Comment by silenceper** [comment]
如果不需要使用企业会话存档功能就设置`CGO_ENABLED=0`，并且sdk版本使用`v2.0.9-rc.1`

**Comment by silenceper** [comment]
@Aicmortal 是否还有问题？

**Comment by silenceper** [comment]
问题我先关闭了，如果有问题再反馈

**Comment by liect** [comment]
不好意思,最近没上,问题已经解决了,升级到2.0.9就好了,并未设置CGO_ENABLED=0
