### ISSUE TITLE
[咨询]在Mac系统是否支持使用会话归档服务

### ISSUE THREAD

**Issue by xiaoyuit** [silenceper/wechat#463]
**请描述您的问题**
1、在Mac系统是否支持使用会话归档服务
2、开启会话归档服务的话在Mac系统上是否可以正常编译

**Comment by silenceper** [comment]
暂只支持在linux环境下编译和运行

**Comment by xiaoyuit** [comment]
> 暂只支持在linux环境下编译和运行

非常感谢回复！
