### ISSUE TITLE
[BUG]  libWeWorkFinanceSdk_C.so cannot open shared object file: 这个功能必须得启用， 不用企业微信都不行吗

### ISSUE THREAD

**Issue by xiusin** [silenceper/wechat#464]
**描述**
```
/tmp/go-build3771466976/b001/exe/main: error while loading shared libraries: libWeWorkFinanceSdk_C.so: cannot open shared object file: No such file or directory
exit status 127

```
我试了2.0.7~9 都会报这个问题，

> 借楼反馈个问题：github.com/silenceper/wechat/v2@v2.0.6/officialaccount/material/material.go:198  这个方法里传入的filename为什么设置为字符串呢， 上传文件得先存到本地再构建参数完成上传， 传入file对象是否可以

**如何复现**
步骤：
1、
2、

**关联日志信息**

**使用的版本**
 - SDK版本: [比如 v0.0.0]

**Comment by silenceper** [comment]
请使用release-2.0分支的最新代码。
filename 目前传递的是一个文件路径地址

**Comment by silenceper** [comment]
@xiusin  楼主看下是否还有这个问题？

**Comment by iWinston** [comment]
v2.0.9-rc.1 还是有这个问题 @silenceper 
回退到v2.0.6之后正常

**Comment by silenceper** [comment]
直接使用release-2.0分支最新代码,go.mod文件中
```
require github.com/silenceper/wechat release-2.0
```

**Comment by iWinston** [comment]
require github.com/silenceper/wechat/v2 release-2.0
@silenceper 验证可行，感谢

**Comment by silenceper** [comment]
好的，这个修复会在下个版本推出。
