### ISSUE TITLE
[Feature] 支持传递golang统一标准的`context.Context`

### ISSUE THREAD

**Issue by okhowang** [silenceper/wechat#468]
**你想要实现的模块或API**

在io操作时使用标准的`context.Context`控制请求取消超时等

**Comment by silenceper** [comment]
这个可以有。
这个可能改动有点大，作为一个较大的版本来发布

**Comment by okhowang** [comment]
可以参考标准库的`sql`包中，提供`XXXContext`版本的新接口保证兼容性
