### ISSUE TITLE
为什么删除菜单老出错？

### ISSUE THREAD

**Issue by cnsd365** [silenceper/wechat#47]
代码：
wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	mu := wc.GetMenu(req, rw)
	mu.DeleteMenu()
出错信息：
runtime error: invalid memory address or nil pointer dereference

**Comment by silenceper** [comment]
是不是没有设置cache

**Comment by cnsd365** [comment]
我没有设置cache呀？是不是需要安装另外一个模块？

**Comment by cnsd365** [comment]
如果用beego框架的话，那cache可以直接使用beego的cache吗？

**Comment by cnsd365** [comment]
memcache := cache.NewMemcache("127.0.0.1:11211")
	memcache.Delete("test")
	wc := wechat.NewWechat(config)

	// 传入request和responseWriter
	server := wc.GetServer(req, rw)
	mu := wc.GetMenu(req, rw)
	mu.DeleteMenu()
还是出错。

**Comment by cnsd365** [comment]
大师出手不凡，果然一语中的，是cache没有设置的原因。问题解决了，非常感谢！

**Comment by cnsd365** [comment]
.\main.go:22:8: cannot use memcache (type "github.com/astaxie/beego/cache".Cache) as type "github.com/silenceper/wechat/cache".Cache in field value:
	"github.com/astaxie/beego/cache".Cache does not implement "github.com/silenceper/wechat/cache".Cache (missing Set method)
错误: 进程退出代码 2.

**Comment by cnsd365** [comment]
总算解决了。还是老老实实下载安装个memocached来用吧哈。谢谢大师了！
