### ISSUE TITLE
[咨询] 2.0.0升级2.0.8后build报错

### ISSUE THREAD

**Issue by LonelySally** [silenceper/wechat#476]
**请描述您的问题**
gomod升级上来后执行build报错,业务没有用到该功能部分.
2021-09-09 14:07:35.087 go build -o ./bin/linux_amd64/business -ldflags "-s -w" main.go
2021-09-09 14:07:36.283 failed to build, os:linux, arch:amd64, error:
# github.com/silenceper/wechat/v2/work
..\..\..\..\go\pkg\mod\github.com\silenceper\wechat\v2@v2.0.8\work\work.go:38:33: undefined: msgaudit.Client
..\..\..\..\go\pkg\mod\github.com\silenceper\wechat\v2@v2.0.8\work\work.go:39:9: undefined: msgaudit.NewClient

**Comment by silenceper** [comment]
先直接使用最新版：
```
require github.com/silenceper/wechat/v2 release-2.0
```

**Comment by LonelySally** [comment]
> 先直接使用最新版：
> 
> ```
> require github.com/silenceper/wechat/v2 release-2.0
> ```

是208版本本身的问题吗?还是我哪里的用法不对

**Comment by silenceper** [comment]
默认引入了一个企业微信的会话存档功能，是以cgo的方式加载，所以导致这个问题。

在最新代码以及增加了条件编译解决，所以可以先使用最新的代码。

**Comment by LonelySally** [comment]
> 默认引入了一个企业微信的会话存档功能，是以cgo的方式加载，所以导致这个问题。
> 
> 在最新代码以及增加了条件编译解决，所以可以先使用最新的代码。

非常感谢.希望文档那边能增加一些demo,退款申请里面的RootCA有点不是很理解指向的是哪个.先琢磨琢磨.
