### ISSUE TITLE
oauth.Redirect 错误

### ISSUE THREAD

**Issue by xie1xiao1jun** [silenceper/wechat#48]
oauth.Redirect 中用到了以下代码[](url)

 ```
   //location 为完整地址，所以不需要request
  http.Redirect(writer, nil, location, 302)
  return nil
```

其中
http.Redirect(writer, nil, location, 302)中第二个参数必须不能为空。我在go1.9的版本上测试报错。

**Comment by silenceper** [comment]
具体错误信息是什么

**Comment by xie1xiao1jun** [comment]
go的Redirect [要使用到r。以下贴出原始定义

func Redirect(w ResponseWriter, r *Request, url string, code int) {
	if u, err := parseURL(url); err == nil {
		//...........
	}
	w.Header().Set("Location", hexEscapeNonASCII(url))
	w.WriteHeader(code)
	if r.Method == "GET" { //就在此处使用的
		note := "<a href=\"" + htmlEscape(url) + "\">" + statusText[code] + "</a>.\n"
		fmt.Fprintln(w, note)
	}
}

**Comment by silenceper** [comment]
调用的panic 的栈信息 贴出来看一下
