### ISSUE TITLE
根据文档例子使用报错

### ISSUE THREAD

**Issue by bufanyun** [silenceper/wechat#488]
使用的官方演示 ：https://silenceper.com/wechat/openplatform/

以下是报错，请问是怎么回事？

app/common/api/test.go:45:27: cannot use func literal (type func("github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) *"github.com/silenceper/wechat/v2/officialaccount/message".Reply) as type func(*"github.com/silenceper/wechat/v2/officialaccount/message".MixMessage) *"github.com/silenceper/wechat/v2/officialaccount/message".Reply in argument to server.SetMessageHandler
note: module requires Go 1.16

**Comment by silenceper** [comment]
例子没有更新哈，应该是下面这种，`msg *message.MixMessage`
```
server.SetMessageHandler(func(msg *message.MixMessage) *message.Reply {
```

**Comment by silenceper** [comment]
@bufanyun  看下是否还有问题

**Comment by bufanyun** [comment]
文档不够详细，建议参考一下：https://www.easywechat.com/
非常看好这个项目，有望成为国内最强的go语言wechat开发包，打造一个强大的社区环境，感谢回复！

<blockquote><div><strong><a href="https://www.easywechat.com/">EasyWeChat - 一个 PHP 微信开发 SDK | EasyWeChat</a></strong></div><div>一个 PHP 微信开发 SDK</div></blockquote>

**Comment by silenceper** [comment]
感谢认可，文档上是需要花点时间来整理
