### ISSUE TITLE
[Feature] 目前是不是没有支持被动回复用户消息

### ISSUE THREAD

**Issue by wangle201210** [silenceper/wechat#515]
公众号配置了回调地址后
用户触发了某些事件
回调的接口是可以被动回复用户消息
请问，目前是否未支持（我翻了下源码没找到）
如果的确没有的话，我考虑提个pr实现下～
[官方文档地址](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html#0)

**Comment by zhujintao** [comment]
可以使用客服消息接口进行异步回复:
mp.GetCustomerMessageManager().Send(message.NewCustomerTextMessage(string(msg.FromUserName), content))
