### ISSUE TITLE
[Feature]如果不同的服务器同时使用access_token会失效

### ISSUE THREAD

**Issue by ZheruiL** [silenceper/wechat#516]
**你想要实现的模块或API**

假如多个服务器同时使用(比如测试服务器和生产服务器)，由于token保存在缓存中，如果服务器1先生成了token1保存，然后服务器2生成了token2，此时token1就失效了，但是服务器1还是会继续使用token1。建议可以在请求收到token失效这个错误的时候可以强制刷新一次token

**Comment by silenceper** [comment]
多服务共用确实有这个问题。
可以自己实现一个 AccessTokenHandle ，自己控制token刷新方式，比如有一个中央的server来负责token的刷新。

**Comment by silenceper** [comment]
没有其他疑问，我就先这个issue了
