### ISSUE TITLE
[Feature]微信小程序提交隐私协议设置

### ISSUE THREAD

**Issue by holdno** [silenceper/wechat#517]
微信小程序提交隐私协议设置
[官方文档](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/privacy_config/set_privacy_setting.html)

目前好像没这个功能？  
没有的话我先写一个后面pr

**Comment by silenceper** [comment]
欢迎贡献pr 👏🏻

**Comment by holdno** [comment]
[pr 518](https://github.com/silenceper/wechat/pull/518)
