### ISSUE TITLE
[BUG] 企业微信 README 例子错误

### ISSUE THREAD

**Issue by yann0917** [silenceper/wechat#519]
**描述**

**如何复现**
步骤：
1、
2、

**关联日志信息**

```bash
image.Image.SdkFileId undefined (type struct { SdkFileID string "json:\"sdkfileid,omitempty\""; Md5Sum string "json:\"md5sum,omitempty\""; FileSize uint32 "json:\"filesize,omitempty\"" } has no field or method SdkFileId, but does have SdkFileID)
internal/services/workWx/msgaudit.go:69:29: item.Emotion.SdkFileId undefined (type struct { Type uint32 "json:\"type,omitempty\""; Width uint32 "json:\"width,omitempty\""; Height uint32 "json:\"height,omitempty\""; ImageSize uint32 "json:\"imagesize,omitempty\""; SdkFileID string "json:\"sdkfileid,omitempty\""; Md5Sum string "json:\"md5sum,omitempty\"" } has no field or method SdkFileId, but does have SdkFileID)

```

**使用的版本**
 - SDK版本: [比如 v0.0.0]
 
![image](https://user-images.githubusercontent.com/25262709/147746611-7c43e8d5-ec12-4199-8a5e-e7150ca09114.png)

应该是 `SdkFileID `

**Comment by silenceper** [comment]
感谢反馈

**Comment by yann0917** [comment]
> 感谢反馈

## 描述

😂 又发现一个问题，拉取媒体资源时还有一点问题，没有填写 `indexbuf`，导致拉取大媒体文件时一直拉不下来导致内存耗尽，拉取小媒体文件时没有问题。

## 解决方案

文档说：媒体消息分片拉取，需要填入每次拉取的索引信息。首次不需要填写，后续每次调用只需要将上次调用返回的outindexbuf填入即可。

正确的方式如下：参考 [NICEXAI/WeWorkFinanceSDK](https://github.com/NICEXAI/WeWorkFinanceSDK/blob/8517415717ad090bb40e8a8a0520da0d362bd67e/example/example.go#L49-L62) 项目的 [example](https://github.com/NICEXAI/WeWorkFinanceSDK/blob/main/example/example.go)已验证可行



![image](https://user-images.githubusercontent.com/25262709/148490286-f1472ee5-f19a-42a8-b289-5a1b0dba40f8.png)

BTW:  NICEXAI/WeWorkFinanceSDK项目的 README 文档也是错误的，已经提 bug 了

 
---

**Comment by silenceper** [comment]
@NICEXAI 帮确认下反馈的这个问题?

**Comment by NICEXAI** [comment]
> indexbuf

这只是一个最简的演示demo, 任何时候拉取文件都必须填写 indexbuf

**Comment by NICEXAI** [comment]
> > indexbuf
> 
> 抱歉，这只是一个最简的演示demo, 任何时候拉取文件都必须填写 indexbuf，我会修改这个示例，避免让你们产生误会

**Comment by NICEXAI** [comment]
#527 文档已更新

**Comment by yann0917** [comment]
> > > indexbuf
> > 
> > 
> > 抱歉，这只是一个最简的演示demo, 任何时候拉取文件都必须填写 indexbuf，我会修改这个示例，避免让你们产生误会

好的，多谢。看到企业客服文档还没整理出来，只能看demo 再看源码。
