### ISSUE TITLE
能否增加一个功能:通过给定的JSON配置文件而生成微信菜单?

### ISSUE THREAD

**Issue by cnsd365** [silenceper/wechat#52]
感觉JSON配置起来非常方便,建议楼主通过提供一个函数:SetMenuByJson(JsonFileName string)来创建菜单,这样最好了.因为菜单可以通过记事本来灵活配置,非常方便的.
感谢楼主的辛勤付出!

**Comment by silenceper** [comment]
这个可以有，也欢迎提交pr 🚀

**Comment by silenceper** [comment]
fix in #261
