### ISSUE TITLE
自定义实现cache的时候，发现获取access_token判断方式

### ISSUE THREAD

**Issue by lala0257** [silenceper/wechat#529]
val := ak.cache.Get(accessTokenCacheKey)
if val != nil {
     accessToken = val.(string)
     return
}
如果val=“”， 那就不是nil

**Comment by houseme** [comment]
> val := ak.cache.Get(accessTokenCacheKey)
> if val != nil {
> accessToken = val.(string)
> return
> }
> 如果val=“”， 那就不是nil

研究一下 `go-redis/redis/v8` 文档

**Comment by johnpoint** [comment]
感觉这里的判断改为判断长度不为0会好一点？

**Comment by houseme** [comment]
> 感觉这里的判断改为判断长度不为0会好一点？

需要俩次判断！看下源码`go-redis/redis/v8`

**Comment by popstk** [comment]
#721  这里现在改成了判断空字符串，但是没法兼容以前自定义cache，
- 以前 自定义cache过期要返回nil
- 现在 自定义cache过期要返回空字符串

**Comment by houseme** [comment]
> #721  这里现在改成了判断空字符串，但是没法兼容以前自定义cache，
> 
> - 以前 自定义cache过期要返回nil
> 
> - 现在 自定义cache过期要返回空字符串
> 
> 

建议自己实现一个，可以参考 #714 pr

**Comment by popstk** [comment]
> > #721  这里现在改成了判断空字符串，但是没法兼容以前自定义cache，
> > 
> > * 以前 自定义cache过期要返回nil
> > * 现在 自定义cache过期要返回空字符串
> 
> 建议自己实现一个，可以参考 #714 pr

我知道怎么实现一个自己的cache，这是一个小版本，应该保证兼容性（兼容两种返回的情况），否则使用自定义cache的用户从v2.1.5及以前升级上来，会导致产生panic

**Comment by houseme** [comment]
> > > #721  这里现在改成了判断空字符串，但是没法兼容以前自定义cache，
> > > 
> > > * 以前 自定义cache过期要返回nil
> > > * 现在 自定义cache过期要返回空字符串
> > 
> > 
> > 建议自己实现一个，可以参考 #714 pr
> 
> 我知道怎么实现一个自己的cache，这是一个小版本，应该保证兼容性（兼容两种返回的情况），否则使用自定义cache的用户从v2.1.5及以前升级上来，会导致产生panic


辛苦提pr 处理吧
