### ISSUE TITLE
[咨询] 公众号带参数二维码

### ISSUE THREAD

**Issue by mztlive** [silenceper/wechat#532]
**请描述您的问题**

不支持获取公众号带参数二维码吗？ 抱歉，我没有找到这个功能的文档

**Comment by silenceper** [comment]
对应的微信文档发一下？api可以搜一下

**Comment by mztlive** [comment]
> 对应的微信文档发一下？api可以搜一下

https://developers.weixin.qq.com/doc/offiaccount/Account_Management/Generating_a_Parametric_QR_Code.html

貌似确实没有

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Account_Management/Generating_a_Parametric_QR_Code.html">微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by silenceper** [comment]
https://github.com/silenceper/wechat/blob/v2/officialaccount/basic/qr.go 
在这个方法里面

<blockquote><img src="https://opengraph.githubassets.com/398efc723d14a55b66e797199ca63a1b1a8340ed29f31726285570e1166120a7/silenceper/wechat" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">wechat/qr.go at v2 · silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>

**Comment by mztlive** [comment]
> https://github.com/silenceper/wechat/blob/v2/officialaccount/basic/qr.go 在这个方法里面
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/780322f4f340459b560bc64118473ed7119636d6c88ac46507f7fa16eafb2cd6/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f333938656663373233643134613535623636653739373139396361363361316231613833343065643239663331373236323835353730653131363631323061372f73696c656e63657065722f776563686174"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[wechat/qr.go at v2 · silenceper/wechat](https://github.com/silenceper/wechat)**WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.

谢谢！

<blockquote><img src="https://opengraph.githubassets.com/6626f55a40f978731414a5a8f502b0bb6013f917c8992ec68a8002260e39ad8f/silenceper/wechat" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">wechat/qr.go at v2 · silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>
