### ISSUE TITLE
[BUG] 公众号调用 GetUserInfo 返回关注过的用户基本信息为”空“数据

### ISSUE THREAD

**Issue by liran** [silenceper/wechat#537]
**描述**
https://github.com/silenceper/wechat/blob/5c4b28acee44faeb2743610ad904c249ee95979f/officialaccount/user/user.go#L66

该函数之前可以返回关注过后的用户基本信息，现在无论是否关注，返回的信息基本都是空的，昵称，头像都没有值。

**如何复现**
步骤：
1、任意一次调用都可以复现，**必现**。

**关联日志信息**
```json
{
  "errcode": 0,
  "errmsg": "",
  "subscribe": 1,
  "openid": "oNgvm6e3iVH_3q72O7oeDreWXfpg",
  "nickname": "",
  "sex": 0,
  "city": "",
  "country": "",
  "province": "",
  "language": "zh_CN",
  "headimgurl": "",
  "subscribe_time": 1618441997,
  "unionid": "",
  "remark": "",
  "groupid": 0,
  "tagid_list": [],
  "subscribe_scene": "ADD_SCENE_QR_CODE",
  "qr_scene": 0,
  "qr_scene_str": ""
}

```

**使用的版本**
 - SDK版本: v2.1.2

**Comment by liran** [comment]
好像是微信官方不再输出 昵称和头像等信息。

https://developers.weixin.qq.com/doc/offiaccount/User_Management/Get_users_basic_information_UnionID.html#UinonId
> 请注意： 20年6月8日起，用户关注来源“微信广告（ADD_SCENE_WECHAT_ADVERTISEMENT）”从“其他（ADD_SCENE_OTHERS）”中拆分给出，2021年12月27日之后，不再输出头像、昵称信息。

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/User_Management/Get_users_basic_information_UnionID.html#UinonId">微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by liran** [comment]
好像只有使用 `scope = snsapi_userinfo` 的授权才可以获取到这些信息。

> https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html">微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by pihc** [comment]
获取用户信息的接口地址换一下就可以了
`userInfoURL     = "https://api.weixin.qq.com/cgi-bin/user/info?access_token=%s&openid=%s&lang=zh_CN"`
换成 
`userInfoURL = "https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN"`

**Comment by ssddn** [comment]
调用GetUserInfo接口返回 &{{48001 api unauthorized rid: 6258f436-04520193-017e4cee} 0   0      0   0 []  0 }
请问这是什么原因？

**Comment by houseme** [comment]
> 调用GetUserInfo接口返回 &{{48001 api unauthorized rid: 6258f436-04520193-017e4cee} 0 0 0 0 [] 0 }
> 请问这是什么原因？

去官方文档查询一下错误码：`48001`是什么 
`48001 | api 功能未授权，请确认公众号已获得该接口，可以在公众平台官网 - 开发者中心页中查看接口权限`
微信公众号错误码：https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Global_Return_Code.html
企业微信的错误码：https://developer.work.weixin.qq.com/document/path/90313

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Global_Return_Code.html">微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>
<blockquote><div><strong><a href="https://developer.work.weixin.qq.com/document/path/90313">全局错误码 - 接口文档 - 企业微信开发者中心</a></strong></div></blockquote>

**Comment by chenyu1990** [comment]
> 获取用户信息的接口地址换一下就可以了 `userInfoURL = "https://api.weixin.qq.com/cgi-bin/user/info?access_token=%s&openid=%s&lang=zh_CN"` 换成 `userInfoURL = "https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN"`

试了，没用。这个问题都没解决，为啥closed了？

**Comment by chenyu1990** [comment]
这个问题都没解决，为啥closed了？
