### ISSUE TITLE
[咨询]公众号如何回复空内容消息，解决提示该公众号提供的服务出现故障，请稍后再试问题

### ISSUE THREAD

**Issue by Light0821** [silenceper/wechat#543]
### 问题描述：
回复消息设置为空字符串时会提示，**该公众号提供的服务出现故障，请稍后再试**，使用到的代码如下

```
return &message.Reply{
	MsgType: message.MsgTypeText,
	MsgData: message.NewText(""),
}
```

**Comment by silenceper** [comment]
有什么log信息吗？

**Comment by Light0821** [comment]
> 有什么log信息吗？

谢谢，感谢回复，具体如下所述。
1. 指定回复内容为空字符串时，日志输出发送给微信用户的消息内容如下，其中`Content`为空了
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/16831868/160310287-8402558f-a0a6-4758-b138-1436932d8e95.png" height="100" width="100">

2. 微信公众号内收到的消息内容为
![IMG_177B560E8DA1-1](https://user-images.githubusercontent.com/16831868/160310452-15f25a76-6927-4081-9b6d-177314f1ae4d.jpeg)

3. 微信公众号的官方文档针对消息回复，有如下的描述，目前看为空时回复的`Content`不是一个空串，可能跟这个有关系
  - 直接回复success（推荐方式） 
  - 直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）
  -   [官方文档](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html)

**Comment by silenceper** [comment]
看一下你的reply是如何写的？  
这里有个例子
```
//设置接收消息的处理方法
server.SetMessageHandler(func(msg *message.MixMessage) *message.Reply {

    //回复消息：演示回复用户发送的消息
    text := message.NewText(msg.Content)
    return &message.Reply{MsgType: message.MsgTypeText, MsgData: text}
})
```

**Comment by Light0821** [comment]
默认回复的代码如下，回复了一个空字符。

```
// 默认消息返回
func (oa *sOfficialAccount) defaultReply() *message.Reply {
	var response string = ""
	return &message.Reply{
		MsgType: message.MsgTypeText,
		MsgData: message.NewText(response),
	}
}
```

**Comment by silenceper** [comment]
非空串是否成功？

**Comment by silenceper** [comment]
返回的`message.Reply`都是经过序列化为xml之后的内容返回的，并不是微信文档中定义的空串

**Comment by Light0821** [comment]
非空串内容时可以的，就空字符串不行。

其实业务上就是想实现，给用户啥都不回复。但啥消息都不会微信会报 `该公众号提供的服务出现故障，请稍后再试`。

**Comment by ssddn** [comment]
直接 return nil 即可

**Comment by silenceper** [comment]
> 直接 return nil 即可

@Light0821 按照这种方式还有问题提吗？

**Comment by Light0821** [comment]
> 

抱歉，回复晚了，回复`nil`  是可以的，问题已经解决了，非常感谢
