### ISSUE TITLE
[咨询]创建小程序码时的path有啥用

### ISSUE THREAD

**Issue by w22296437978** [silenceper/wechat#545]
创建二维码时，页面路径有两个 ，page和path，这个path有啥用
![image](https://user-images.githubusercontent.com/39508539/162874053-19e608c7-c9a3-4cd2-972b-79d0a0943139.png)

**Comment by w22296437978** [comment]
我将路径设置到path上，进入的是小程序的主页

**Comment by houseme** [comment]
> 我将路径设置到path上，进入的是小程序的主页

微信官方文档 [小程序码 /createQRCode](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.createQRCode.html)
