### ISSUE TITLE
[咨询] 关于access_token

### ISSUE THREAD

**Issue by StyleBeau** [silenceper/wechat#564]
想知道  本sdk 是如何监控redis  中的access_token；当我删除redis中的access_token ；在没有任何访问接口；在1分钟左右会自动补齐access_token到redis；咨询这个问题是因为我的access_token总是超过调用频率限制>2000次，如果是redis原因；在排查之后更换了阿里云的redis  还是出现调用频率限制>2000次。能否解答下

**Comment by houseme** [comment]
> 想知道 本sdk 是如何监控redis 中的access_token；当我删除redis中的access_token ；在没有任何访问接口；在1分钟左右会自动补齐access_token到redis；咨询这个问题是因为我的access_token总是超过调用频率限制>2000次，如果是redis原因；在排查之后更换了阿里云的redis 还是出现调用频率限制>2000次。能否解答下

accessToken 存储有效期： `expires := resAccessToken.ExpiresIn - 1500`，是不是一个公众号APPID ，在多处使用，A服务先获取，B又获取，这样A的token有效期就只有五分钟。是不是这个原因？

**Comment by StyleBeau** [comment]
我看源码里面确实是 expires := resAccessToken.ExpiresIn - 1500 ；我这是一个新的小程序   只是用在了silenceper/wechat上 并没有多处使用

**Comment by StyleBeau** [comment]
> > 想知道 本sdk 是如何监控redis 中的access_token；当我删除redis中的access_token ；在没有任何访问接口；在1分钟左右会自动补齐access_token到redis；咨询这个问题是因为我的access_token总是超过调用频率限制>2000次，如果是redis原因；在排查之后更换了阿里云的redis 还是出现调用频率限制>2000次。能否解答下
> 
> accessToken 存储有效期： `expires := resAccessToken.ExpiresIn - 1500`，是不是一个公众号APPID ，在多处使用，A服务先获取，B又获取，这样A的token有效期就只有五分钟。是不是这个原因？

我看源码里面确实是 expires := resAccessToken.ExpiresIn - 1500 ；我这是一个新的小程序 只是用在了silenceper/wechat上 并没有多处使用；

**Comment by houseme** [comment]
> > > 想知道 本sdk 是如何监控redis 中的access_token；当我删除redis中的access_token ；在没有任何访问接口；在1分钟左右会自动补齐access_token到redis；咨询这个问题是因为我的access_token总是超过调用频率限制>2000次，如果是redis原因；在排查之后更换了阿里云的redis 还是出现调用频率限制>2000次。能否解答下
> > 
> > 
> > accessToken 存储有效期： `expires := resAccessToken.ExpiresIn - 1500`，是不是一个公众号APPID ，在多处使用，A服务先获取，B又获取，这样A的token有效期就只有五分钟。是不是这个原因？
> 
> 我看源码里面确实是 expires := resAccessToken.ExpiresIn - 1500 ；我这是一个新的小程序 只是用在了silenceper/wechat上 并没有多处使用；

测试环境和生产环境都是这个小程序吗？
