### ISSUE TITLE
[BUG]是否应该使用自定义的 logrus 对象？

### ISSUE THREAD

**Issue by kvii** [silenceper/wechat#569]
**描述**
本库在[init 函数](https://github.com/silenceper/wechat/blob/v2/wechat.go#L21)中修改了 logrus 库的全局配置。
对于在本库之前 init 的库，那些库对 logrus 的全局设置会被本库的 init 函数覆盖掉。
建议不要使用全局的 logrus 对象，改为自己单独创建 logrus 对象并提供相应的配置方法。

**如何复现**
步骤：
1. 克隆 https://github.com/kvii/wechat_issue.git 工程。该工程复现了描述中说明的情况。
2. 执行 `make run` 命令。观察控制台输出。
3. 当导入本库时，由于其他库对于 logrus 的全局配置被覆盖，导致本不应该打印到控制台上的日志被打印出来了。

**关联日志信息**
```
cd a && go run .
zz/b 库将 logrus 的输出设置成了 io.Discard。
所有 logrus 函数都不会向控制台打印信息。
导入了 wechat 包时的行为
INFO[0000] 因为 zz/b 库的 init 方法。这句 log 应该不会显示在控制台上。       
aa/a 刚刚使用 logrus 向控制台打印了一条信息。

cd a2 && go run .
zz/b 库将 logrus 的输出设置成了 io.Discard。
所有 logrus 函数都不会向控制台打印信息。
没导入 wechat 包时的行为
aa/a2 刚刚使用 logrus 向控制台打印了一条信息。
```

**使用的版本**
 - github.com/silenceper/wechat/v2 v2.1.3

**Comment by houseme** [comment]
欢迎提PR
