### ISSUE TITLE
希望新增一个批量获取用户信息的接口

### ISSUE THREAD

**Issue by tucke** [silenceper/wechat#57]
https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token=ACCESS_TOKEN
批量获取用户虽然也可以通过作者封装的单个获取api 实现，但是数量一多，效率的弊端很明显

**Comment by silenceper** [comment]
可以有，也欢迎pr

**Comment by aikangs** [comment]
https://github.com/silenceper/wechat/pull/106
