### ISSUE TITLE
[BUG] github.com/go-redis/redis/v8 最新版本为 8.11.5，但是go.mod依赖的版本确实8.11.6

### ISSUE THREAD

**Issue by kaiiak** [silenceper/wechat#571]
**描述**

**如何复现**
步骤：
https://pkg.go.dev/github.com/go-redis/redis/v8
**关联日志信息**
<img width="392" alt="截屏2022-06-14 18 35 22" src="https://user-images.githubusercontent.com/2832687/173558027-67e00071-0e57-4563-bf16-3b5fa813e32b.png">

**使用的版本**
 - SDK版本: [比如 v2.1.3]

**Comment by houseme** [comment]
这个不是BUG，只是依赖的master分支最新的代码。

**Comment by houseme** [comment]
拉最新的代码试试，`go-redis` 已经会滚到 `8.11.5` 
```shell
go get -u -v github.com/silenceper/wechat/v2@adf142d
```

@kaiiak
