### ISSUE TITLE
[BUG]企业微信给客户打标签参数有误

### ISSUE THREAD

**Issue by bailey5239** [silenceper/wechat#574]
**描述**
企业微信给客户打标签参数有误

{
	"userid":"zhangsan",
	"external_userid":"woAJ2GCAAAd1NPGHKSD4wKmE8Aabj9AAA",
	"add_tag":["TAGID1","TAGID2"],
	"remove_tag":["TAGID3","TAGID4"]
}

代码是 user_id

**Comment by houseme** [comment]
> **描述** 企业微信给客户打标签参数有误
> 
> { "userid":"zhangsan", "external_userid":"woAJ2GCAAAd1NPGHKSD4wKmE8Aabj9AAA", "add_tag":["TAGID1","TAGID2"], "remove_tag":["TAGID3","TAGID4"] }
> 
> 代码是 user_id

欢迎提PR
