### ISSUE TITLE
[BUG] Whether debugging information can be closed

### ISSUE THREAD

**Issue by iwctwbai** [silenceper/wechat#578]
```
func (srv *Server) Serve() error {
	if !srv.Validate() {
		log.Error("Validate Signature Failed.")
		return fmt.Errorf("请求校验失败")
	}

	echostr, exists := srv.GetQuery("echostr")
	if exists {
		srv.String(echostr)
		return nil
	}

	response, err := srv.handleRequest()
	if err != nil {
		return err
	}

	// debug print request msg
	log.Debugf("request msg =%s", string(srv.RequestRawXMLMsg))

	return srv.buildResponse(response)
}
```

### Something about this```log.Debugf```

**Comment by houseme** [comment]
> ```
> func (srv *Server) Serve() error {
> 	if !srv.Validate() {
> 		log.Error("Validate Signature Failed.")
> 		return fmt.Errorf("请求校验失败")
> 	}
> 
> 	echostr, exists := srv.GetQuery("echostr")
> 	if exists {
> 		srv.String(echostr)
> 		return nil
> 	}
> 
> 	response, err := srv.handleRequest()
> 	if err != nil {
> 		return err
> 	}
> 
> 	// debug print request msg
> 	log.Debugf("request msg =%s", string(srv.RequestRawXMLMsg))
> 
> 	return srv.buildResponse(response)
> }
> ```
> 
> ### 上述代码所有`log.Debugf`相关

欢迎提PR

**Comment by iwctwbai** [comment]
@houseme 好的,查验下 #579

**Comment by iwctwbai** [comment]
@houseme 另外发现项目``` util ``` 包对错误处理很粗糙，```panic&&recover``` 与返回错误混用 建议你们做下处理
