### ISSUE TITLE
[BUG] 请不要使用 go-redis 8.11.6 测试版本

### ISSUE THREAD

**Issue by duxphp** [silenceper/wechat#581]
使用 v8.11.6-0.20220405070650-99c79f7041fc 版本
会导致 redis 的不断错误 请使用正式版本 8.11.5
redis: 2022/07/19 05:05:05 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 127.0.0.1:40426->127.0.0.1:6379: i/o timeout

**Comment by silenceper** [comment]
@duxphp 你这边验证8.11.5 版本是符合预期的是吗？

**Comment by houseme** [comment]
> 使用 v8.11.6-0.20220405070650-99c79f7041fc 版本 会导致 redis 的不断错误 请使用正式版本 8.11.5 redis: 2022/07/19 05:05:05 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 127.0.0.1:40426->127.0.0.1:6379: i/o timeout

拉最新的代码试试，`go-redis` 已经会滚到 `8.11.5` 
```shell
go get -u -v github.com/silenceper/wechat/v2@adf142d
```

**Comment by houseme** [comment]
> > 使用 v8.11.6-0.20220405070650-99c79f7041fc 版本 会导致 redis 的不断错误 请使用正式版本 8.11.5 redis: 2022/07/19 05:05:05 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 127.0.0.1:40426->127.0.0.1:6379: i/o timeout
> 
> 拉最新的代码试试，`go-redis` 已经会滚到 `8.11.5`
> 
> ```shell
> go get -u -v github.com/silenceper/wechat/v2@adf142d
> ```

@duxphp
