### ISSUE TITLE
处理用户回调函数返回为nil的情况，否则提示“该公众号暂时无法提供服务，请稍后再试”

### ISSUE THREAD

**Issue by waro163** [silenceper/wechat#586]
https://github.com/silenceper/wechat/blob/adf142dac2eb48a51033b10445d217a238349b12/officialaccount/server/server.go#L227-L230
此处代码中，当用户回调函数返回nil的时候，是想实现微信开发文档中的无回复效果。但是此处代码会导致服务号提示异常。

添加代码如下：
```go
if reply == nil {
    // do nothing
    srv.String("success")
    return nil
    }
`


ref.
假如服务器无法保证在五秒内处理并回复，必须做出下述回复，这样微信服务器才不会对此作任何处理，并且不会发起重试（这种情况下，可以使用客服消息接口进行异步回复），否则，将出现严重的错误提示。详见下面说明：
1、直接回复success（推荐方式） 2、直接回复空串（指字节长度为0的空字符串，而不是 XML 结构体中 content 字段的内容为空）
一旦遇到以下情况，微信都会在公众号会话中，向用户下发系统提示“该公众号暂时无法提供服务，请稍后再试”：

**Comment by silenceper** [comment]
@waro163 看其他人回复nil是ok的。
https://github.com/silenceper/wechat/issues/543#issuecomment-1119721537

正常回复内容ok吗

**Comment by waro163** [comment]
@silenceper 
正常回复消息是OK的。
但是在测试返回为nil的情况下，还是会出现公众号无法提供服务提示。
运行环境：
微信公众平台测试号，消息为明文方式。

见下图：
![6493af96-8571-4ecb-8d16-3e09a88f4245](https://user-images.githubusercontent.com/12164123/180692496-11363b66-1235-42e5-bf6c-4e7fd5137290.jpg)

服务器部分输出：
```
DEBU[0016] validate signature, timestamp=1658718771, nonce=1300612379 
DEBU[0016] request msg =<xml><ToUserName><![CDATA[gh_d049d0472d74]]></ToUserName>
<FromUserName><![CDATA[oJlus55n0z6moe2LXDnZWMJkaq7I]]></FromUserName>
<CreateTime>1658718770</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[测试]]></Content>
<MsgId>23747143716747800</MsgId>
</xml> 
DEBU[0016] response msg =<nil> 
```

**Comment by waro163** [comment]
更新：
我研究了下，对于某些web框架，如果没有任何返回，则会自动在ResponseWriter中添加“Content-Length”为0的空字符串返回。这也是为什么 issue #543 中解决的该问题的原因。
但是在某些框架或者自定义设置中，没有返回该字段并不会设置或者设置为其他，这导致微信并没有收到预定的返回，导致出错。

查看源码可以看到当用户处理函数返回nil时，并没有做任何处理，返回结果完全依赖于框架如何处理。
因此此处需要对用户处理函数返回为空时，进行“success”或者空字符串的回应

**Comment by silenceper** [comment]
@waro163 可以的。推荐返回`success `，你愿意修复该问题吗？

**Comment by waro163** [comment]
修复该问题相对比较简单，我稍后提交一个pr。
多问一下有没有类似开发者社区一样讨论群，关于bug修改，性能提升或者加入新特性等方面的讨论？

**Comment by silenceper** [comment]
现在没有维护社群，有消息都在issue沟通

**Comment by silenceper** [comment]
fixed in #589
