### ISSUE TITLE
很多地方写的太死,调试不方便

### ISSUE THREAD

**Issue by bolls** [silenceper/wechat#59]
比如说调试接受到数据
```
type Server struct {
	*context.Context

	openID string

	messageHandler func(message.MixMessage) *message.Reply

	requestRawXMLMsg  []byte
	requestMsg        message.MixMessage
	responseRawXMLMsg []byte
	responseMsg       interface{}

	isSafeMode bool
	random     []byte
	nonce      string
	timestamp  int64
}
```
私有不太舒服,建议部分改成大写,或者添加一些公开函数获取.

**Comment by silenceper** [comment]
嗯嗯，加一个debug模式可能方便一点

**Comment by silenceper** [comment]
#83

**Comment by SLance** [comment]
逼我用反射。。。

**Comment by SLance** [comment]
> 逼我用反射。。。

因为业务关系，必须拿到原始数据，但httprouter的Request.Body又无法二次读取
一开始的办法是用MixMessage重组xml.Marshal()但这种方法浪费性能

所以逼着我用reflect。。。

**Comment by silenceper** [comment]
https://github.com/silenceper/wechat/blob/6fe797765f808a0d55c613312c8d1bf4ee7f3b5c/officialaccount/server/server.go#L32

在v2版本作为一个公开参数
