### ISSUE TITLE
[咨询]微信开放平台 如何代小程序使用手机号登录

### ISSUE THREAD

**Issue by YangCSir** [silenceper/wechat#622]
**请描述您的问题**
![image](https://user-images.githubusercontent.com/21410207/194746875-894749dd-2965-4253-8ff9-975a95db8d2e.png)
目前配置了开放平台的参数，没有办法能够调用到小程序下面的GetPhoneNumber的方法
/github.com/silenceper/wechat/v2@v2.1.4-rc.1/miniprogram/auth/auth.go:148

**Comment by houseme** [comment]
多看文档，以及瞅瞅代码。

**Comment by YangCSir** [comment]
https://github.com/silenceper/wechat/pull/623
