### ISSUE TITLE
微信公众号绑定API 在哪里？

### ISSUE THREAD

**Issue by magixmin** [silenceper/wechat#640]
我在做第一步绑定功能，我们公众号绑定API在哪里
<img width="877" alt="image" src="https://user-images.githubusercontent.com/68672136/211262478-e0fb241b-cfa4-4fd0-926b-f7358c174766.png">

**Comment by houseme** [comment]
文档有

**Comment by magixmin** [comment]
> 文档有

麻烦请问在哪？没找到

**Comment by silenceper** [comment]
没看到微信公众号有提供API
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html

**Comment by silenceper** [comment]
@magixmin 你截图的这个操作是在微信公众号页面操作的，没有看到微信有提供这个操作的API

https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html">接入概述 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by magixmin** [comment]
这个我看了。URL 输入那个URL 接受这个事件

**Comment by magixmin** [comment]
//处理推送消息以及事件
	r.Any("/api/v1/serve", exampleOffAccount.Serve)
这个么

**Comment by magixmin** [comment]
![image](https://user-images.githubusercontent.com/68672136/211281014-6f0fddaf-af30-4b08-904c-2fd44016c689.png)
可以找下官方的demo，其实就是响应一个很简单的值
看看这个页面：https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html

```php
private function checkSignature()
{
    $signature = $_GET["signature"];
    $timestamp = $_GET["timestamp"];
    $nonce = $_GET["nonce"];
	
    $token = TOKEN;
    $tmpArr = array($token, $timestamp, $nonce);
    sort($tmpArr, SORT_STRING);
    $tmpStr = implode( $tmpArr );
    $tmpStr = sha1( $tmpStr );
    
    if( $tmpStr == $signature ){
        return true;
    }else{
        return false;
    }
}
```

demo下载地址：https://res.wx.qq.com/op_res/-serEQ6xSDVIjfoOHcX78T1JAYX-pM_fghzfiNYoD8uHVd3fOeC0PC_pvlg4-kmP

**Comment by magixmin** [comment]
直接用这个呗。我们里面没有
