### ISSUE TITLE
[BUG] 同一 wechat.Wechat 实例下获取的 MiniProgram 以及 OfficialAccount access_token 会互相覆盖

### ISSUE THREAD

**Issue by johnpoint** [silenceper/wechat#647]
**描述**

1. 如果使用同一个appid进行实例化wechat.Wechat ，同时使用 MiniProgram 和 OfficialAccount 的能力，创建的两个实例在刷新 access_token 时产生冲突。会出现类似 MiniProgram 实例刷新后 OfficialAccount 实例 access_token 失效的情况
2. 目前代码中默认实现的 AccessTokenHandle 锁在内部实现，对分布式部署支持较差

**使用的版本**
 - v2.1.4
 
**解决思路**
1. 可以尝试在通过wechat.Wechat 获取下级实例时，使用同一个 key 存储 access_token，并且加入分布式锁的实现

**Comment by houseme** [comment]
1、`同一个appid进行实例化wechat.Wechat ，同时使用 MiniProgram 和 OfficialAccount 的能力 ` 同一个`appID` 支持公众号和小诚信吗？

2、可以设置不同`redis`的`DB` 区分一下

**Comment by johnpoint** [comment]
1. 实际使用时可以的，甚至用的是一套 appid 和 appsecrt
2. 使用不同的db没有意义，因为实际上出现异常是因为 MiniProgram  实例刷新了 token 导致了 OfficialAccount 的 token 失效

**Comment by johnpoint** [comment]
这边用的是OCR的接口，这个接口小程序和公众号都能调用

这么想来，那应该在库里面的小程序部分也实现OCR的相关函数才是正确的选择

**Comment by houseme** [comment]
应该是初始化2个wechat对象使用，而不是使用一个，token存储的在redis对应设置的db中。

**Comment by johnpoint** [comment]
不是，现在的问题是同一个appid只应该有一个access_token有效

在2023年2月9日二月 下午4:53，houseme写道：

**Comment by houseme** [comment]
贴一下代码吧，可能咱们俩的理解不一致。这个appid 是OCR服务的吗？还是某一个公众号或小程序呢？

**Comment by johnpoint** [comment]
就是说 现在调用 公众号和小程序 接口所使用的 appid 是同一个 appid，是小程序的 appid

**Comment by realpg** [comment]
> 就是说 现在调用 公众号和小程序 接口所使用的 appid 是同一个 appid，是小程序的 appid

你的公众号和小程序为什么会是同一个appid？

**Comment by johnpoint** [comment]
> > 就是说 现在调用 公众号和小程序 接口所使用的 appid 是同一个 appid，是小程序的 appid
> 
> 你的公众号和小程序为什么会是同一个appid？

我用的是小程序的appid
小程序调用ocr相关的接口还没实现

**Comment by silenceper** [comment]
这种场景，不是是更建议搞一个中心化的服务来刷新accessToken？ 即自己实现
https://github.com/silenceper/wechat/blob/v2/credential/access_token.go#L6
```
type AccessTokenHandle interface {
	GetAccessToken() (accessToken string, err error)
}
```

现在默认的都是被动的


<blockquote><img src="https://opengraph.githubassets.com/3aec5a1b0e885ebb4f446d0946c376ecabe4987418411801d715d6c9c5666bd0/silenceper/wechat" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">wechat/access_token.go at v2 · silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>

**Comment by johnpoint** [comment]
> 这种场景，不是是更建议搞一个中心化的服务来刷新accessToken？ 即自己实现 https://github.com/silenceper/wechat/blob/v2/credential/access_token.go#L6
> 
> ```
> type AccessTokenHandle interface {
> 	GetAccessToken() (accessToken string, err error)
> }
> ```
> 
> 现在默认的都是被动的
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/39b72064dd44b11d615a9b84d76122a1b016ba24670c582971cfd09557ab01e4/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f336165633561316230653838356562623466343436643039343663333736656361626534393837343138343131383031643731356436633963353636366264302f73696c656e63657065722f776563686174"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[wechat/access_token.go at v2 · silenceper/wechat](https://github.com/silenceper/wechat)**WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.

建立一个独立的服务是一种解决方式，这个issue出现的原因是小程序sdk里面没有实现ocr相关的方法

<blockquote><img src="https://opengraph.githubassets.com/3aec5a1b0e885ebb4f446d0946c376ecabe4987418411801d715d6c9c5666bd0/silenceper/wechat" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/silenceper/wechat">wechat/access_token.go at v2 · silenceper/wechat</a></strong></div><div>WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.</div></blockquote>

**Comment by silenceper** [comment]
我其实没有理解，
第一点 为什么不能复用代码，实现ocr实例是需要的，然后具体的的实现比如接口请求以及反回值，就复用
第二点 你这个两个实例为什么会刷新，除非是两套存储了

**Comment by johnpoint** [comment]
> 我其实没有理解， 第一点 为什么不能复用代码，实现ocr实例是需要的，然后具体的的实现比如接口请求以及反回值，就复用 第二点 你这个两个实例为什么会刷新，除非是两套存储了

第一点，复用代码是指？
第二点，因为小程序和公众号默认实现的自动刷新token的函数内置了不一样的key

**Comment by realpg** [comment]
> > > 就是说 现在调用 公众号和小程序 接口所使用的 appid 是同一个 appid，是小程序的 appid
> > 
> > 
> > 你的公众号和小程序为什么会是同一个appid？
> 
> 我用的是小程序的appid 小程序调用ocr相关的接口还没实现

就是说，你用了魔改的办法，用小程序的appid去初始化公众号，因为这两者针对某个功能的API是一致的？这显然不是标准用法，自己魔改非支持的用法，有问题是很正常的。


即使你这么用也不是不行，直接用Handle自己搞个外部token就好了，或者两个token用一个cache


还有就是，小程序ocr接口还没实现，公众号有同样能用的代码，你直接就把这部分代码迁移到小程序下，简单测试然后提个pr，不就实现了，不要一味索取

甚至不用你去琢磨逻辑，只需要搞好上下文别出bug了

**Comment by silenceper** [comment]
> 第一点，复用代码是指？

这个复用：https://github.com/silenceper/wechat/pull/648#discussion_r1104679037

**Comment by johnpoint** [comment]
> > > > 就是说 现在调用 公众号和小程序 接口所使用的 appid 是同一个 appid，是小程序的 appid
> > > 
> > > 
> > > 你的公众号和小程序为什么会是同一个appid？
> > 
> > 
> > 我用的是小程序的appid 小程序调用ocr相关的接口还没实现
> 
> 就是说，你用了魔改的办法，用小程序的appid去初始化公众号，因为这两者针对某个功能的API是一致的？这显然不是标准用法，自己魔改非支持的用法，有问题是很正常的。
> 
> 即使你这么用也不是不行，直接用Handle自己搞个外部token就好了，或者两个token用一个cache
> 
> 还有就是，小程序ocr接口还没实现，公众号有同样能用的代码，你直接就把这部分代码迁移到小程序下，简单测试然后提个pr，不就实现了，不要一味索取
> 
> 甚至不用你去琢磨逻辑，只需要搞好上下文别出bug了

有没有可能我已经提pr了 #648

**Comment by liushuai05** [comment]
> > 这种场景，不是是更建议搞一个中心化的服务来刷新accessToken？ 即自己实现 https://github.com/silenceper/wechat/blob/v2/credential/access_token.go#L6
> > ```
> > type AccessTokenHandle interface {
> > 	GetAccessToken() (accessToken string, err error)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 现在默认的都是被动的
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/39b72064dd44b11d615a9b84d76122a1b016ba24670c582971cfd09557ab01e4/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f336165633561316230653838356562623466343436643039343663333736656361626534393837343138343131383031643731356436633963353636366264302f73696c656e63657065722f776563686174"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[wechat/access_token.go at v2 · silenceper/wechat](https://github.com/silenceper/wechat)**WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.
> 
> 建立一个独立的服务是一种解决方式，这个issue出现的原因是小程序sdk里面没有实现ocr相关的方法
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/39b72064dd44b11d615a9b84d76122a1b016ba24670c582971cfd09557ab01e4/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f336165633561316230653838356562623466343436643039343663333736656361626534393837343138343131383031643731356436633963353636366264302f73696c656e63657065722f776563686174"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[wechat/access_token.go at v2 · silenceper/wechat](https://github.com/silenceper/wechat)**WeChat SDK for Go （微信SDK：简单、易用）. Contribute to silenceper/wechat development by creating an account on GitHub.

这个有没有具体一点的代码参考呢大佬，我这边研究了大半天都没搞明白，我的代码是下面这样的，但是报错了不知道哪里没写对：

```
// 实现access_token从中间服务器获取
type cred struct {
	Type int
}

func (a cred) New(typea int) credential.AccessTokenHandle {
	return cred{
		Type: typea,
	}
}

type AccessTokenRule struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

// 从中间服务器获取
func (a cred) GetAccessToken() (string, error) {
	// 请求服务器对应地址获取accesstoken
	url := fmt.Sprintf("http://xxxx.com/getToken?getType=%d", a.Type)
	tokenBody, tokenErr := httpr.Get(url)
	if tokenErr != nil {
		return "", tokenErr
	}

	defer tokenBody.Body.Close()

	restoken := AccessTokenRule{}
	decoder := json.NewDecoder(tokenBody.Body)
	if decodeErr := decoder.Decode(&restoken); decodeErr != nil {
		// log.WithFields(log.Fields{"error": decodeErr}).Warn("json解密-GetAccessToken")
		// return ""

		if tokenErr != nil {
			return "", tokenErr
		}
	}

	if restoken.Code != 200 {
		// log.WithFields(log.Fields{"error": tokenResp}).Warn("官方提示-GetAccessToken")
		// return ""

		if tokenErr != nil {
			return "", tokenErr
		}
	}
	fmt.Println(restoken.Token)
	TokenMw, err := base64.StdEncoding.DecodeString(restoken.Token)
	if err != nil {
		return "", err
	}

	encrypted, err := rsa.PrivateKeyDecrypt([]byte(TokenMw))
	if err != nil {
		return "", err
	}

	// 如果获取到了accesstoken，则进行解密，如果没获取到则报错

	return string(encrypted), nil
}

func (r *GrClientController) init() {
	account = wc.GetMiniProgram(cfg)
	var creda cred

	account.SetAccessTokenHandle = creda.New(1)

	isInit = true
}

```

![图片](https://github.com/silenceper/wechat/assets/26994692/58360e59-d8cd-44bb-af1c-29f5e79a8735)

**Comment by johnpoint** [comment]
```go
account.SetAccessTokenHandle(credential.NewStableAccessToken("appid", "key", "", w.Cache))
```
是这样

**Comment by liushuai05** [comment]
> ```go
> account.SetAccessTokenHandle(credential.NewStableAccessToken("appid", "key", "", w.Cache))
> ```
> 
> 是这样

感谢大佬，已经搞定了，测试使用正常
由于我们的一个平台下同时有2个小程序下面是我的写法：
```
account.SetAccessTokenHandle(creda.New(1))
```
