### ISSUE TITLE
发送模板参数需要更新

### ISSUE THREAD

**Issue by gateslu** [silenceper/wechat#66]
`//Message 发送的模板消息内容
type Message struct {
        ...
	MiniProgram struct {
		AppID    string `json:"appid"` //所需跳转到的小程序appid（该小程序appid必须与发模板消息的公众号是绑定关联关系）
		**PagePath string `json:"path"`**  //**官网是pagepath，但是实际上是path，**所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar）
	} `json:"miniprogram"` //可选,跳转至小程序地址
}`

**Comment by gateslu** [comment]
额，上面乱了，就是PagePath stringjson:"pagepath"这里，需要将pagepath修改成path

**Comment by silenceper** [comment]
欢迎提个pr 😀
