### ISSUE TITLE
[咨询]这段代码不是很理解？是不是有bug？

### ISSUE THREAD

**Issue by ikilobyte** [silenceper/wechat#679]
https://github.com/silenceper/wechat/blob/d92cd355330cf77ab54b518a156e3c8082975367/openplatform/miniprogram/component/component.go#L36-L47

其中第39行，`err != nil `，返回一个`nil` 这是为什么？

**Comment by houseme** [comment]
提 PR  修复一下，包括下面的方法也可以一起修复

**Comment by ikilobyte** [comment]
pr #680

**Comment by houseme** [comment]
> pr #680

@silenceper 辛苦看下这个 pr

**Comment by silenceper** [comment]
already fix in #680
