### ISSUE TITLE
[咨询] 不能处理微信小程序消息推送吗？

### ISSUE THREAD

**Issue by mztlive** [silenceper/wechat#683]
【文档地址】https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url

我只在文档和例子中找到了公众号的消息推送，但是小程序的没有。
是没有封装吗？

**Comment by houseme** [comment]
> 【文档地址】https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url
> 
> 我只在文档和例子中找到了公众号的消息推送，但是小程序的没有。 是没有封装吗？

建议根据小程序消息的 api 接口地址搜索一下，如果有，那就是实现了，否则就是没有，也欢迎来提 PR ，欢迎

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url">消息推送 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by mztlive** [comment]
> > 【文档地址】https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url
> > 我只在文档和例子中找到了公众号的消息推送，但是小程序的没有。 是没有封装吗？
> 
> 建议根据小程序消息的 api 接口地址搜索一下，如果有，那就是实现了，否则就是没有，也欢迎来提 PR ，欢迎
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/28b6c956b7d5ee69dd802ab9ad0eb1a3b652089913dd3e665e193d17a73c9f86/68747470733a2f2f7265732e77782e71712e636f6d2f612f77785f6665642f6173736574732f7265732f4e5449344d5755352e69636f">**[消息推送 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url)**微信开发者平台文档

不是接口，是被动接收来自微信的消息。 我看似乎是没有的。

<blockquote><img src="https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico" width="48" align="right"><div><strong><a href="https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#option-url">消息推送 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by jony4** [comment]
这个消息推送，会推送什么内容过来？

**Comment by mztlive** [comment]
> 这个消息推送，会推送什么内容过来？

和公众号的类似，各种事件，如果要做小程序订阅消息就必须依赖推送

**Comment by houseme** [comment]
@mztlive 来搞个PR吧

**Comment by houseme** [comment]
@mztlive  是不是需要这个 https://github.com/silenceper/wechat/pull/429

**Comment by ccfish86** [comment]
#713 
手搓了一个，看能不能用
