### ISSUE TITLE
[咨询]GetAccessTokenContext是否存在未判断为空字符的情况

### ISSUE THREAD

**Issue by Silas-Zhu** [silenceper/wechat#684]
**请描述您的问题**
![image](https://github.com/silenceper/wechat/assets/9334080/f45272ed-b01f-4e7c-8bd1-a4181fa255af)
如图所示，从缓存中取出的是空字符，这种情况也应该当做nil处理

**Comment by houseme** [comment]
可以提 pr 改进一波
