### ISSUE TITLE
关于语音识别字段添加

### ISSUE THREAD

**Issue by kanyways** [silenceper/wechat#69]
如果用户在微信公众号打开语音识别，微信返回的消息中会有Recognition  string  `xml:"Recognition"`

所以请在message实体中添加，个人已经完成了相关添加。

**Comment by silenceper** [comment]
好的，欢迎pr 👍

**Comment by kanyways** [comment]
为什么还没有更新呢。弄得我每次更新vendor之后都需要修改下。


```go
type MixMessage struct {
	CommonToken

	//基本消息
	MsgID        int64   `xml:"MsgId"`
	Content      string  `xml:"Content"`
	Recognition  string  `xml:"Recognition"`
	//后面就不写了
```

主要是自己弄了一个骚气的微信机器人。方便这帮兄弟自己去浪，输入语言去浪。

**Comment by silenceper** [comment]
如果你已经修改了，你可以把代码push过来，我merge一下

**Comment by kanyways** [comment]
其实不是不给你弄，我不会用。哈哈哈。刚才搜索了一番才知道怎么弄的。汗颜。
