### ISSUE TITLE
写的挺好，我先复制文件上传的代码用用

### ISSUE THREAD

**Issue by niaiwomattt** [silenceper/wechat#7]

**Comment by silenceper** [comment]
欢迎PR  😄

**Comment by niaiwomattt** [comment]
PostMultipartForm 函数的 filed字段为什么不用 引用传递 ？就是前面加 *号。

**Comment by niaiwomattt** [comment]
type MultipartFormField struct {
	IsFile    bool
	Fieldname string
	Value     []byte
	Filename  string
}

这个结构体变成
type MultipartFormField struct {
	IsFile    bool
	Name string
	Value     *[]byte
}
更好些，如果是文件就是文件流，如果是字段就是字段值
