### ISSUE TITLE
[BUG] 企业微信--客户联系--获取客户群详情的返回值没有考虑有返回state值的情况

### ISSUE THREAD

**Issue by Lumiaqian** [silenceper/wechat#716]
**描述**
企业微信--客户联系--获取客户群详情的返回值少了state字段
**如何复现**
步骤：
(https://developer.work.weixin.qq.com/document/path/92229#%E9%99%84%E5%BD%95%EF%BC%9A%E8%8E%B7%E5%8F%96%E5%AE%A2%E6%88%B7%E7%BE%A4%E8%AF%A6%E6%83%85%EF%BC%8C%E8%BF%94%E5%9B%9Estate%E5%8F%82%E6%95%B0) 
如果在配置入群方式时，配置了state参数，那么在[获取客户群详情](https://developer.work.weixin.qq.com/document/path/92229#19412)时，通过该方式入群的成员，会额外获取到相应的state参数

**关联日志信息**

**使用的版本**
 - SDK版本: [v2.1.5]

**Comment by silenceper** [comment]
fixed in #717
