### ISSUE TITLE
[BUG] 企业微信--通讯录--获取用户详情

### ISSUE THREAD

**Issue by Lumiaqian** [silenceper/wechat#722]
**描述**

**如何复现**
步骤：
1、使用userid读取成员信息
2、抛出userid not found

**关联日志信息**
![image](https://github.com/silenceper/wechat/assets/20120178/1f8904e0-f424-4a47-aef5-0383ad296bee)
<img width="1277" alt="image" src="https://github.com/silenceper/wechat/assets/20120178/329ac6e2-f693-4b60-bb06-06ebdcec756c">

**使用的版本**
 - SDK版本: [v2.1.5]

**Comment by Lumiaqian** [comment]
#723

**Comment by silenceper** [comment]
fixed in #723
