### ISSUE TITLE
[BUG] work GetExternalUserDetail return params json Unmarshal Error

### ISSUE THREAD

**Issue by Lumiaqian** [silenceper/wechat#731]
**描述**

**如何复现**
步骤：
<img width="404" alt="image" src="https://github.com/silenceper/wechat/assets/20120178/341fac2f-787e-4731-8f05-bc74afe58401">
<img width="904" alt="image" src="https://github.com/silenceper/wechat/assets/20120178/5a786130-e337-4417-b2c9-feb21eb1f4b6">
<img width="865" alt="image" src="https://github.com/silenceper/wechat/assets/20120178/7d384e6b-4e0d-4e0e-8415-175ab794cf41">

**关联日志信息**
json Unmarshal Error, err=json: cannot unmarshal number into Go struct field WechatChannel.follow_user.wechat_channels.source of type string

**使用的版本**
 - SDK版本: [比如 v2.1.5]

**Comment by houseme** [comment]
欢迎提 pr 修复哦
