### ISSUE TITLE
"json Unmarshal Error, err=json: cannot unmarshal number into Go struct field FollowUser.follow_user.createtime of type string"

### ISSUE THREAD

**Issue by ourines** [silenceper/wechat#748]
企业微信返回的是uint64
https://github.com/silenceper/wechat/blob/9df943df69f0d33a5f1ecaf5e8fd1ecaa3288aa1/work/externalcontact/external_user.go#L74C10-L74C10

**Comment by houseme** [comment]
欢迎提pr修复哦
