### ISSUE TITLE
[BUG]cache 干什么用的，不配置吧不行么？panic: cache is ineed

### ISSUE THREAD

**Issue by echo-music** [silenceper/wechat#767]
**描述**
小程序配置文件未配置cache 直接报错
panic: cache is ineed

**如何复现**
步骤：

WxMiniProgram: wx.NewWechat().GetMiniProgram(&miniConfig.Config{
			AppID:     c.Wechat.MiniProgram.AppID,
			AppSecret: c.Wechat.MiniProgram.AppSecret,
			Cache: nil,
}),

**关联日志信息**
panic: cache is ineed

**使用的版本**
 - SDK版本: [比如 v0.0.0]

**Comment by houseme** [comment]
和腾讯交互的token存在哪里呢？存文件吗？
