### ISSUE TITLE
公众号新增模板消息接口，新增了参数，暂未支持

### ISSUE THREAD

**Issue by qietugou** [silenceper/wechat#782]
**描述**

**如何复现**
步骤：
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html#2

新参数 keyword_name_list 并必填

**关联日志信息**

**使用的版本**
 - SDK 版本：[比如 v2.1.6]

**Comment by houseme** [comment]
@qietugou 辛苦大佬完善一下，辛苦辛苦 🙏🙏🙏

**Comment by qietugou** [comment]
@houseme 好了，麻烦大佬审核下，需要这个方法
