### ISSUE TITLE
[咨询]40001的问题请教

### ISSUE THREAD

**Issue by jianjianxu** [silenceper/wechat#790]
我的代码：
```
var m = cache.NewMemory()
w := wechat.NewWechat()
c := &offConfig.Config{
	AppID:     AppID,
	AppSecret: AppSecret,
	Cache:     m,
}
oa := w.GetOfficialAccount(c)
_, err := oa.GetAccessToken()
...
...
...
templateMessage := &message.TemplateMessage{
	ToUser:     to,
	TemplateID: TemplateID,
	URL:        URL,
	Data:       msgData,
}
_, err = oa.GetTemplate().Send(templateMessage)
```
每次给一个人发一条，就执行一次上面的代码。频次高一点点就会报40001：

> 发送失败: template msg send error : errcode=40001 , errmsg=invalid credential, access_token is invalid or not latest, could get access_token by getStableAccessToken, more details at https://mmbizurl.cn/s/JtxxFh33r rid: 66bac357-63c29597-4c205ae0！

我查了一下，是accesstoken频繁申请失效导致的。

我看了一下wechat自己源码`oa.GetAccessToken()`，里面的cache就是会根据不同公众号进行保存token

如果按这里的机制，按道理说不应该会重复申请access_token的。

请教一下，是我的写法应该怎么改正一下吗？

或者如果不得不用`getStableAccessToken`，请教应该怎么写合理

**Comment by houseme** [comment]
请问是多台机器部署吗？建议Cache使用redis存储，如果多台机器会重复创建，前一个创建的token就相互过期
