### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yangyl12345** [silenceper/wechat#804]
**描述**
开发微信小程序，获取稳定版接口调用凭据，在获取 cache 的 key 为“”的情况下，仍然会返回结果，而不是直接走代码流程，去微信服务器获取 token，存到 redis

**如何复现**
步骤：
1、
2、

**关联日志信息**

**使用的版本**
 - SDK 版本：[比如 v0.0.0]
v2.1.7

**Comment by houseme** [comment]
辛苦提PR修复一下，@yangyl12345 

https://github.com/silenceper/wechat/blob/3fbe8634d99d21353024aa9da175d823a54a5183/credential/default_access_token.go#L129 
可以参考 

https://github.com/silenceper/wechat/blob/3fbe8634d99d21353024aa9da175d823a54a5183/credential/default_access_token.go#L66

L129行方法 参考 L66方法 修复一下，但是一般情况key存在，为啥没值呢？
