### ISSUE TITLE
建议：给 redis 增加一个使用外部连接的接口

### ISSUE THREAD

**Issue by cool222** [silenceper/wechat#86]
可以给 cache/redis.go 增加一个指定Redis 对象的方法，由项目统一配置和管理，就不需要组件单独连接了。
//NewRedis 实例化
func SetRedis(pool *redis.Pool) *Redis {
return &Redis{pool}
}

**Comment by silenceper** [comment]
是可以的

**Comment by salamander-mh** [comment]
@cool222 
```
myCache := &wechatCache.Redis{}
myCache.SetConn(cache.GetPool())
```
这样不就行了

**Comment by silenceper** [comment]
已经有了
