### ISSUE TITLE
小程序的 code2Session api希望加上去

### ISSUE THREAD

**Issue by getpu** [silenceper/wechat#92]
const code2SessionUrl = "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"

const openInfoType = 0

type Wechat struct {
	*wechat.Wechat
}

type Code2Session struct {
	Openid       string      `json:"openid"`
	SessionKey   string      `json:"session_key"`
	Unionid      string      `json:"unionid"`
	ErrCode      int64       `json:"errcode"`
	ErrMsg       string      `json:"errMsg"`
}

func (w *Wechat) GetCode2Session(code string) (result Code2Session, err error) {
	urlStr := fmt.Sprintf(code2SessionUrl, w.Context.AppID, w.Context.AppSecret, code)
	var response []byte
	response, err = util.HTTPGet(urlStr)
	if err != nil {
		return
	}

	err = json.Unmarshal(response, &result)
	if err != nil {
		return
	}
	if result.ErrCode != 0 {
		err = fmt.Errorf("GetCode2Session error : errcode=%v , errmsg=%v", result.ErrCode, result.ErrMsg)
		return
	}
    return
}

**Comment by silenceper** [comment]
欢迎pr

**Comment by silenceper** [comment]
已有
