### ISSUE TITLE
 在docker中

### ISSUE THREAD

**Issue by dupengshenyang** [silenceper/wechat#94]
Get https://api.weixin.qq.com/sns/oauth2/access_token?appid=&secret=&code=123&grant_type=authorization_code: x509: certificate signed by unknown authority

**Comment by silenceper** [comment]
你用的是哪个镜像?

`FROM centurylink/ca-certs`

用这个镜像试一下

**Comment by dupengshenyang** [comment]
alpine:3.2 
改了一下包 好使了  但是有另一个问题了
![image](https://user-images.githubusercontent.com/8084847/48237178-75a9df00-e400-11e8-8ff6-f6f5e4f70240.png)
![image](https://user-images.githubusercontent.com/8084847/48237189-80647400-e400-11e8-8a64-196a020cca13.png)
![image](https://user-images.githubusercontent.com/8084847/48237202-8eb29000-e400-11e8-8562-7952a9516c84.png)
code确实是没用过的，但是一直提示40163

**Comment by silenceper** [comment]
肯定在哪里已经被使用过了一次了，这个需要你跟踪了，在使用到code的地方打几个日志看看
